// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newActivePassword(db *gorm.DB, opts ...gen.DOOption) activePassword {
	_activePassword := activePassword{}

	_activePassword.activePasswordDo.UseDB(db, opts...)
	_activePassword.activePasswordDo.UseModel(&models.ActivePassword{})

	tableName := _activePassword.activePasswordDo.TableName()
	_activePassword.ALL = field.NewAsterisk(tableName)
	_activePassword.ID = field.NewString(tableName, "id")
	_activePassword.FormID = field.NewString(tableName, "formId")
	_activePassword.Name = field.NewString(tableName, "name")
	_activePassword.Password = field.NewString(tableName, "password")
	_activePassword.IsValid = field.NewBool(tableName, "isValid")
	_activePassword.ExpireAt = field.NewTime(tableName, "expireAt")
	_activePassword.CreatedAt = field.NewTime(tableName, "createdAt")
	_activePassword.UsableUpto = field.NewInt(tableName, "usableUpto")
	_activePassword.Form = activePasswordBelongsToForm{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Form", "models.Form"),
		Project: struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}
			Forms struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Project", "models.Project"),
			Team: struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Form.Project.Team", "models.Team"),
				Plan: struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.Plan", "models.Plan"),
					Coupons: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons", "models.Coupon"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
						},
					},
					Features: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Features", "models.Feature"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Features.Plan", "models.Plan"),
						},
					},
					Teams: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Teams", "models.Team"),
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Forms", "models.Form"),
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Projects", "models.Project"),
				},
				Transactions: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.Transactions", "models.Transaction"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.Transactions.Team", "models.Team"),
					},
				},
			},
			Forms: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Project.Forms", "models.Form"),
			},
		},
		Team: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Team", "models.Team"),
		},
		ActivePasswords: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.ActivePasswords", "models.ActivePassword"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.ActivePasswords.Form", "models.Form"),
			},
		},
		Edges: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Edges", "models.Edge"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.Form", "models.Form"),
			},
			SourceNode: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Form.Edges.SourceNode", "models.Question"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Form", "models.Form"),
				},
				Options: struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Options", "models.QuestionOption"),
					Question: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Edges.SourceNode.Options.Question", "models.Question"),
					},
				},
				OutgoingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.OutgoingEdges", "models.Edge"),
				},
				IncomingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.IncomingEdges", "models.Edge"),
				},
			},
			TargetNode: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.TargetNode", "models.Question"),
			},
		},
		Questions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Questions", "models.Question"),
		},
		Responses: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Responses", "models.Response"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Responses.Form", "models.Form"),
			},
		},
	}

	_activePassword.fillFieldMap()

	return _activePassword
}

type activePassword struct {
	activePasswordDo

	ALL        field.Asterisk
	ID         field.String
	FormID     field.String
	Name       field.String
	Password   field.String
	IsValid    field.Bool
	ExpireAt   field.Time
	CreatedAt  field.Time
	UsableUpto field.Int
	Form       activePasswordBelongsToForm

	fieldMap map[string]field.Expr
}

func (a activePassword) Table(newTableName string) *activePassword {
	a.activePasswordDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a activePassword) As(alias string) *activePassword {
	a.activePasswordDo.DO = *(a.activePasswordDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *activePassword) updateTableName(table string) *activePassword {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.FormID = field.NewString(table, "formId")
	a.Name = field.NewString(table, "name")
	a.Password = field.NewString(table, "password")
	a.IsValid = field.NewBool(table, "isValid")
	a.ExpireAt = field.NewTime(table, "expireAt")
	a.CreatedAt = field.NewTime(table, "createdAt")
	a.UsableUpto = field.NewInt(table, "usableUpto")

	a.fillFieldMap()

	return a
}

func (a *activePassword) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *activePassword) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["formId"] = a.FormID
	a.fieldMap["name"] = a.Name
	a.fieldMap["password"] = a.Password
	a.fieldMap["isValid"] = a.IsValid
	a.fieldMap["expireAt"] = a.ExpireAt
	a.fieldMap["createdAt"] = a.CreatedAt
	a.fieldMap["usableUpto"] = a.UsableUpto

}

func (a activePassword) clone(db *gorm.DB) activePassword {
	a.activePasswordDo.ReplaceConnPool(db.Statement.ConnPool)
	a.Form.db = db.Session(&gorm.Session{Initialized: true})
	a.Form.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a activePassword) replaceDB(db *gorm.DB) activePassword {
	a.activePasswordDo.ReplaceDB(db)
	a.Form.db = db.Session(&gorm.Session{})
	return a
}

type activePasswordBelongsToForm struct {
	db *gorm.DB

	field.RelationField

	Project struct {
		field.RelationField
		Team struct {
			field.RelationField
			Plan struct {
				field.RelationField
				Coupons struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Features struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Teams struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
			Projects struct {
				field.RelationField
			}
			Transactions struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
		}
		Forms struct {
			field.RelationField
		}
	}
	Team struct {
		field.RelationField
	}
	ActivePasswords struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
	Edges struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
		SourceNode struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			Options struct {
				field.RelationField
				Question struct {
					field.RelationField
				}
			}
			OutgoingEdges struct {
				field.RelationField
			}
			IncomingEdges struct {
				field.RelationField
			}
		}
		TargetNode struct {
			field.RelationField
		}
	}
	Questions struct {
		field.RelationField
	}
	Responses struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
}

func (a activePasswordBelongsToForm) Where(conds ...field.Expr) *activePasswordBelongsToForm {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a activePasswordBelongsToForm) WithContext(ctx context.Context) *activePasswordBelongsToForm {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a activePasswordBelongsToForm) Session(session *gorm.Session) *activePasswordBelongsToForm {
	a.db = a.db.Session(session)
	return &a
}

func (a activePasswordBelongsToForm) Model(m *models.ActivePassword) *activePasswordBelongsToFormTx {
	return &activePasswordBelongsToFormTx{a.db.Model(m).Association(a.Name())}
}

func (a activePasswordBelongsToForm) Unscoped() *activePasswordBelongsToForm {
	a.db = a.db.Unscoped()
	return &a
}

type activePasswordBelongsToFormTx struct{ tx *gorm.Association }

func (a activePasswordBelongsToFormTx) Find() (result *models.Form, err error) {
	return result, a.tx.Find(&result)
}

func (a activePasswordBelongsToFormTx) Append(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a activePasswordBelongsToFormTx) Replace(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a activePasswordBelongsToFormTx) Delete(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a activePasswordBelongsToFormTx) Clear() error {
	return a.tx.Clear()
}

func (a activePasswordBelongsToFormTx) Count() int64 {
	return a.tx.Count()
}

func (a activePasswordBelongsToFormTx) Unscoped() *activePasswordBelongsToFormTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type activePasswordDo struct{ gen.DO }

type IActivePasswordDo interface {
	gen.SubQuery
	Debug() IActivePasswordDo
	WithContext(ctx context.Context) IActivePasswordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IActivePasswordDo
	WriteDB() IActivePasswordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IActivePasswordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IActivePasswordDo
	Not(conds ...gen.Condition) IActivePasswordDo
	Or(conds ...gen.Condition) IActivePasswordDo
	Select(conds ...field.Expr) IActivePasswordDo
	Where(conds ...gen.Condition) IActivePasswordDo
	Order(conds ...field.Expr) IActivePasswordDo
	Distinct(cols ...field.Expr) IActivePasswordDo
	Omit(cols ...field.Expr) IActivePasswordDo
	Join(table schema.Tabler, on ...field.Expr) IActivePasswordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IActivePasswordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IActivePasswordDo
	Group(cols ...field.Expr) IActivePasswordDo
	Having(conds ...gen.Condition) IActivePasswordDo
	Limit(limit int) IActivePasswordDo
	Offset(offset int) IActivePasswordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IActivePasswordDo
	Unscoped() IActivePasswordDo
	Create(values ...*models.ActivePassword) error
	CreateInBatches(values []*models.ActivePassword, batchSize int) error
	Save(values ...*models.ActivePassword) error
	First() (*models.ActivePassword, error)
	Take() (*models.ActivePassword, error)
	Last() (*models.ActivePassword, error)
	Find() ([]*models.ActivePassword, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActivePassword, err error)
	FindInBatches(result *[]*models.ActivePassword, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.ActivePassword) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IActivePasswordDo
	Assign(attrs ...field.AssignExpr) IActivePasswordDo
	Joins(fields ...field.RelationField) IActivePasswordDo
	Preload(fields ...field.RelationField) IActivePasswordDo
	FirstOrInit() (*models.ActivePassword, error)
	FirstOrCreate() (*models.ActivePassword, error)
	FindByPage(offset int, limit int) (result []*models.ActivePassword, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IActivePasswordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a activePasswordDo) Debug() IActivePasswordDo {
	return a.withDO(a.DO.Debug())
}

func (a activePasswordDo) WithContext(ctx context.Context) IActivePasswordDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a activePasswordDo) ReadDB() IActivePasswordDo {
	return a.Clauses(dbresolver.Read)
}

func (a activePasswordDo) WriteDB() IActivePasswordDo {
	return a.Clauses(dbresolver.Write)
}

func (a activePasswordDo) Session(config *gorm.Session) IActivePasswordDo {
	return a.withDO(a.DO.Session(config))
}

func (a activePasswordDo) Clauses(conds ...clause.Expression) IActivePasswordDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a activePasswordDo) Returning(value interface{}, columns ...string) IActivePasswordDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a activePasswordDo) Not(conds ...gen.Condition) IActivePasswordDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a activePasswordDo) Or(conds ...gen.Condition) IActivePasswordDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a activePasswordDo) Select(conds ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a activePasswordDo) Where(conds ...gen.Condition) IActivePasswordDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a activePasswordDo) Order(conds ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a activePasswordDo) Distinct(cols ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a activePasswordDo) Omit(cols ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a activePasswordDo) Join(table schema.Tabler, on ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a activePasswordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a activePasswordDo) RightJoin(table schema.Tabler, on ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a activePasswordDo) Group(cols ...field.Expr) IActivePasswordDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a activePasswordDo) Having(conds ...gen.Condition) IActivePasswordDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a activePasswordDo) Limit(limit int) IActivePasswordDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a activePasswordDo) Offset(offset int) IActivePasswordDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a activePasswordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IActivePasswordDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a activePasswordDo) Unscoped() IActivePasswordDo {
	return a.withDO(a.DO.Unscoped())
}

func (a activePasswordDo) Create(values ...*models.ActivePassword) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a activePasswordDo) CreateInBatches(values []*models.ActivePassword, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a activePasswordDo) Save(values ...*models.ActivePassword) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a activePasswordDo) First() (*models.ActivePassword, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActivePassword), nil
	}
}

func (a activePasswordDo) Take() (*models.ActivePassword, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActivePassword), nil
	}
}

func (a activePasswordDo) Last() (*models.ActivePassword, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActivePassword), nil
	}
}

func (a activePasswordDo) Find() ([]*models.ActivePassword, error) {
	result, err := a.DO.Find()
	return result.([]*models.ActivePassword), err
}

func (a activePasswordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.ActivePassword, err error) {
	buf := make([]*models.ActivePassword, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a activePasswordDo) FindInBatches(result *[]*models.ActivePassword, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a activePasswordDo) Attrs(attrs ...field.AssignExpr) IActivePasswordDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a activePasswordDo) Assign(attrs ...field.AssignExpr) IActivePasswordDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a activePasswordDo) Joins(fields ...field.RelationField) IActivePasswordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a activePasswordDo) Preload(fields ...field.RelationField) IActivePasswordDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a activePasswordDo) FirstOrInit() (*models.ActivePassword, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActivePassword), nil
	}
}

func (a activePasswordDo) FirstOrCreate() (*models.ActivePassword, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.ActivePassword), nil
	}
}

func (a activePasswordDo) FindByPage(offset int, limit int) (result []*models.ActivePassword, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a activePasswordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a activePasswordDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a activePasswordDo) Delete(models ...*models.ActivePassword) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *activePasswordDo) withDO(do gen.Dao) *activePasswordDo {
	a.DO = *do.(*gen.DO)
	return a
}
