// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newCoupon(db *gorm.DB, opts ...gen.DOOption) coupon {
	_coupon := coupon{}

	_coupon.couponDo.UseDB(db, opts...)
	_coupon.couponDo.UseModel(&models.Coupon{})

	tableName := _coupon.couponDo.TableName()
	_coupon.ALL = field.NewAsterisk(tableName)
	_coupon.ID = field.NewString(tableName, "id")
	_coupon.Type = field.NewString(tableName, "type")
	_coupon.DiscountType = field.NewString(tableName, "discountType")
	_coupon.PlanID = field.NewString(tableName, "planId")
	_coupon.Amount = field.NewFloat64(tableName, "amount")
	_coupon.UseLeft = field.NewInt(tableName, "useLeft")
	_coupon.Plan = couponBelongsToPlan{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Plan", "models.Plan"),
		Coupons: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Plan.Coupons", "models.Coupon"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Coupons.Plan", "models.Plan"),
			},
		},
		Features: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Plan.Features", "models.Feature"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Features.Plan", "models.Plan"),
			},
		},
		Teams: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
			Forms struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}
			Projects struct {
				field.RelationField
			}
			Transactions struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Plan.Teams", "models.Team"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Teams.Plan", "models.Plan"),
			},
			Forms: struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Plan.Teams.Forms", "models.Form"),
				Project: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Project", "models.Project"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Project.Team", "models.Team"),
					},
					Forms: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Project.Forms", "models.Form"),
					},
				},
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Team", "models.Team"),
				},
				ActivePasswords: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.ActivePasswords", "models.ActivePassword"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.ActivePasswords.Form", "models.Form"),
					},
				},
				Edges: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Edges", "models.Edge"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.Form", "models.Form"),
					},
					SourceNode: struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode", "models.Question"),
						Form: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Form", "models.Form"),
						},
						Options: struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Options", "models.QuestionOption"),
							Question: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Options.Question", "models.Question"),
							},
						},
						OutgoingEdges: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
						},
						IncomingEdges: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
						},
					},
					TargetNode: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.TargetNode", "models.Question"),
					},
				},
				Questions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Questions", "models.Question"),
				},
				Responses: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Responses", "models.Response"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Responses.Form", "models.Form"),
					},
				},
			},
			Projects: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Teams.Projects", "models.Project"),
			},
			Transactions: struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Plan.Teams.Transactions", "models.Transaction"),
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Plan.Teams.Transactions.Team", "models.Team"),
				},
			},
		},
	}

	_coupon.fillFieldMap()

	return _coupon
}

type coupon struct {
	couponDo

	ALL          field.Asterisk
	ID           field.String
	Type         field.String
	DiscountType field.String
	PlanID       field.String
	Amount       field.Float64
	UseLeft      field.Int
	Plan         couponBelongsToPlan

	fieldMap map[string]field.Expr
}

func (c coupon) Table(newTableName string) *coupon {
	c.couponDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coupon) As(alias string) *coupon {
	c.couponDo.DO = *(c.couponDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coupon) updateTableName(table string) *coupon {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Type = field.NewString(table, "type")
	c.DiscountType = field.NewString(table, "discountType")
	c.PlanID = field.NewString(table, "planId")
	c.Amount = field.NewFloat64(table, "amount")
	c.UseLeft = field.NewInt(table, "useLeft")

	c.fillFieldMap()

	return c
}

func (c *coupon) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coupon) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["id"] = c.ID
	c.fieldMap["type"] = c.Type
	c.fieldMap["discountType"] = c.DiscountType
	c.fieldMap["planId"] = c.PlanID
	c.fieldMap["amount"] = c.Amount
	c.fieldMap["useLeft"] = c.UseLeft

}

func (c coupon) clone(db *gorm.DB) coupon {
	c.couponDo.ReplaceConnPool(db.Statement.ConnPool)
	c.Plan.db = db.Session(&gorm.Session{Initialized: true})
	c.Plan.db.Statement.ConnPool = db.Statement.ConnPool
	return c
}

func (c coupon) replaceDB(db *gorm.DB) coupon {
	c.couponDo.ReplaceDB(db)
	c.Plan.db = db.Session(&gorm.Session{})
	return c
}

type couponBelongsToPlan struct {
	db *gorm.DB

	field.RelationField

	Coupons struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
	}
	Features struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
	}
	Teams struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
		Forms struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}
		Projects struct {
			field.RelationField
		}
		Transactions struct {
			field.RelationField
			Team struct {
				field.RelationField
			}
		}
	}
}

func (a couponBelongsToPlan) Where(conds ...field.Expr) *couponBelongsToPlan {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a couponBelongsToPlan) WithContext(ctx context.Context) *couponBelongsToPlan {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a couponBelongsToPlan) Session(session *gorm.Session) *couponBelongsToPlan {
	a.db = a.db.Session(session)
	return &a
}

func (a couponBelongsToPlan) Model(m *models.Coupon) *couponBelongsToPlanTx {
	return &couponBelongsToPlanTx{a.db.Model(m).Association(a.Name())}
}

func (a couponBelongsToPlan) Unscoped() *couponBelongsToPlan {
	a.db = a.db.Unscoped()
	return &a
}

type couponBelongsToPlanTx struct{ tx *gorm.Association }

func (a couponBelongsToPlanTx) Find() (result *models.Plan, err error) {
	return result, a.tx.Find(&result)
}

func (a couponBelongsToPlanTx) Append(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a couponBelongsToPlanTx) Replace(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a couponBelongsToPlanTx) Delete(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a couponBelongsToPlanTx) Clear() error {
	return a.tx.Clear()
}

func (a couponBelongsToPlanTx) Count() int64 {
	return a.tx.Count()
}

func (a couponBelongsToPlanTx) Unscoped() *couponBelongsToPlanTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type couponDo struct{ gen.DO }

type ICouponDo interface {
	gen.SubQuery
	Debug() ICouponDo
	WithContext(ctx context.Context) ICouponDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICouponDo
	WriteDB() ICouponDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICouponDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICouponDo
	Not(conds ...gen.Condition) ICouponDo
	Or(conds ...gen.Condition) ICouponDo
	Select(conds ...field.Expr) ICouponDo
	Where(conds ...gen.Condition) ICouponDo
	Order(conds ...field.Expr) ICouponDo
	Distinct(cols ...field.Expr) ICouponDo
	Omit(cols ...field.Expr) ICouponDo
	Join(table schema.Tabler, on ...field.Expr) ICouponDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICouponDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICouponDo
	Group(cols ...field.Expr) ICouponDo
	Having(conds ...gen.Condition) ICouponDo
	Limit(limit int) ICouponDo
	Offset(offset int) ICouponDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICouponDo
	Unscoped() ICouponDo
	Create(values ...*models.Coupon) error
	CreateInBatches(values []*models.Coupon, batchSize int) error
	Save(values ...*models.Coupon) error
	First() (*models.Coupon, error)
	Take() (*models.Coupon, error)
	Last() (*models.Coupon, error)
	Find() ([]*models.Coupon, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Coupon, err error)
	FindInBatches(result *[]*models.Coupon, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Coupon) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICouponDo
	Assign(attrs ...field.AssignExpr) ICouponDo
	Joins(fields ...field.RelationField) ICouponDo
	Preload(fields ...field.RelationField) ICouponDo
	FirstOrInit() (*models.Coupon, error)
	FirstOrCreate() (*models.Coupon, error)
	FindByPage(offset int, limit int) (result []*models.Coupon, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICouponDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c couponDo) Debug() ICouponDo {
	return c.withDO(c.DO.Debug())
}

func (c couponDo) WithContext(ctx context.Context) ICouponDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c couponDo) ReadDB() ICouponDo {
	return c.Clauses(dbresolver.Read)
}

func (c couponDo) WriteDB() ICouponDo {
	return c.Clauses(dbresolver.Write)
}

func (c couponDo) Session(config *gorm.Session) ICouponDo {
	return c.withDO(c.DO.Session(config))
}

func (c couponDo) Clauses(conds ...clause.Expression) ICouponDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c couponDo) Returning(value interface{}, columns ...string) ICouponDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c couponDo) Not(conds ...gen.Condition) ICouponDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c couponDo) Or(conds ...gen.Condition) ICouponDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c couponDo) Select(conds ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c couponDo) Where(conds ...gen.Condition) ICouponDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c couponDo) Order(conds ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c couponDo) Distinct(cols ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c couponDo) Omit(cols ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c couponDo) Join(table schema.Tabler, on ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c couponDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICouponDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c couponDo) RightJoin(table schema.Tabler, on ...field.Expr) ICouponDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c couponDo) Group(cols ...field.Expr) ICouponDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c couponDo) Having(conds ...gen.Condition) ICouponDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c couponDo) Limit(limit int) ICouponDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c couponDo) Offset(offset int) ICouponDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c couponDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICouponDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c couponDo) Unscoped() ICouponDo {
	return c.withDO(c.DO.Unscoped())
}

func (c couponDo) Create(values ...*models.Coupon) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c couponDo) CreateInBatches(values []*models.Coupon, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c couponDo) Save(values ...*models.Coupon) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c couponDo) First() (*models.Coupon, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Coupon), nil
	}
}

func (c couponDo) Take() (*models.Coupon, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Coupon), nil
	}
}

func (c couponDo) Last() (*models.Coupon, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Coupon), nil
	}
}

func (c couponDo) Find() ([]*models.Coupon, error) {
	result, err := c.DO.Find()
	return result.([]*models.Coupon), err
}

func (c couponDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Coupon, err error) {
	buf := make([]*models.Coupon, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c couponDo) FindInBatches(result *[]*models.Coupon, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c couponDo) Attrs(attrs ...field.AssignExpr) ICouponDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c couponDo) Assign(attrs ...field.AssignExpr) ICouponDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c couponDo) Joins(fields ...field.RelationField) ICouponDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c couponDo) Preload(fields ...field.RelationField) ICouponDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c couponDo) FirstOrInit() (*models.Coupon, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Coupon), nil
	}
}

func (c couponDo) FirstOrCreate() (*models.Coupon, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Coupon), nil
	}
}

func (c couponDo) FindByPage(offset int, limit int) (result []*models.Coupon, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c couponDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c couponDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c couponDo) Delete(models ...*models.Coupon) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *couponDo) withDO(do gen.Dao) *couponDo {
	c.DO = *do.(*gen.DO)
	return c
}
