// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newEdge(db *gorm.DB, opts ...gen.DOOption) edge {
	_edge := edge{}

	_edge.edgeDo.UseDB(db, opts...)
	_edge.edgeDo.UseModel(&models.Edge{})

	tableName := _edge.edgeDo.TableName()
	_edge.ALL = field.NewAsterisk(tableName)
	_edge.ID = field.NewString(tableName, "id")
	_edge.FormID = field.NewString(tableName, "form_id")
	_edge.SourceNodeID = field.NewString(tableName, "source_node_id")
	_edge.TargetNodeID = field.NewString(tableName, "target_node_id")
	_edge.Condition = field.NewString(tableName, "condition")
	_edge.Form = edgeBelongsToForm{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Form", "models.Form"),
		Project: struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}
			Forms struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Project", "models.Project"),
			Team: struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Form.Project.Team", "models.Team"),
				Plan: struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.Plan", "models.Plan"),
					Coupons: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons", "models.Coupon"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
						},
					},
					Features: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Features", "models.Feature"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Features.Plan", "models.Plan"),
						},
					},
					Teams: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Teams", "models.Team"),
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Forms", "models.Form"),
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Projects", "models.Project"),
				},
				Transactions: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.Transactions", "models.Transaction"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.Transactions.Team", "models.Team"),
					},
				},
			},
			Forms: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Project.Forms", "models.Form"),
			},
		},
		Team: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Team", "models.Team"),
		},
		ActivePasswords: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.ActivePasswords", "models.ActivePassword"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.ActivePasswords.Form", "models.Form"),
			},
		},
		Edges: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Edges", "models.Edge"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.Form", "models.Form"),
			},
			SourceNode: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Form.Edges.SourceNode", "models.Question"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Form", "models.Form"),
				},
				Options: struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Options", "models.QuestionOption"),
					Question: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Edges.SourceNode.Options.Question", "models.Question"),
					},
				},
				OutgoingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.OutgoingEdges", "models.Edge"),
				},
				IncomingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.IncomingEdges", "models.Edge"),
				},
			},
			TargetNode: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.TargetNode", "models.Question"),
			},
		},
		Questions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Questions", "models.Question"),
		},
		Responses: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Responses", "models.Response"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Responses.Form", "models.Form"),
			},
		},
	}

	_edge.SourceNode = edgeBelongsToSourceNode{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("SourceNode", "models.Question"),
	}

	_edge.TargetNode = edgeBelongsToTargetNode{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TargetNode", "models.Question"),
	}

	_edge.fillFieldMap()

	return _edge
}

type edge struct {
	edgeDo

	ALL          field.Asterisk
	ID           field.String
	FormID       field.String
	SourceNodeID field.String
	TargetNodeID field.String
	Condition    field.String
	Form         edgeBelongsToForm

	SourceNode edgeBelongsToSourceNode

	TargetNode edgeBelongsToTargetNode

	fieldMap map[string]field.Expr
}

func (e edge) Table(newTableName string) *edge {
	e.edgeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e edge) As(alias string) *edge {
	e.edgeDo.DO = *(e.edgeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *edge) updateTableName(table string) *edge {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewString(table, "id")
	e.FormID = field.NewString(table, "form_id")
	e.SourceNodeID = field.NewString(table, "source_node_id")
	e.TargetNodeID = field.NewString(table, "target_node_id")
	e.Condition = field.NewString(table, "condition")

	e.fillFieldMap()

	return e
}

func (e *edge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *edge) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["form_id"] = e.FormID
	e.fieldMap["source_node_id"] = e.SourceNodeID
	e.fieldMap["target_node_id"] = e.TargetNodeID
	e.fieldMap["condition"] = e.Condition

}

func (e edge) clone(db *gorm.DB) edge {
	e.edgeDo.ReplaceConnPool(db.Statement.ConnPool)
	e.Form.db = db.Session(&gorm.Session{Initialized: true})
	e.Form.db.Statement.ConnPool = db.Statement.ConnPool
	e.SourceNode.db = db.Session(&gorm.Session{Initialized: true})
	e.SourceNode.db.Statement.ConnPool = db.Statement.ConnPool
	e.TargetNode.db = db.Session(&gorm.Session{Initialized: true})
	e.TargetNode.db.Statement.ConnPool = db.Statement.ConnPool
	return e
}

func (e edge) replaceDB(db *gorm.DB) edge {
	e.edgeDo.ReplaceDB(db)
	e.Form.db = db.Session(&gorm.Session{})
	e.SourceNode.db = db.Session(&gorm.Session{})
	e.TargetNode.db = db.Session(&gorm.Session{})
	return e
}

type edgeBelongsToForm struct {
	db *gorm.DB

	field.RelationField

	Project struct {
		field.RelationField
		Team struct {
			field.RelationField
			Plan struct {
				field.RelationField
				Coupons struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Features struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Teams struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
			Projects struct {
				field.RelationField
			}
			Transactions struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
		}
		Forms struct {
			field.RelationField
		}
	}
	Team struct {
		field.RelationField
	}
	ActivePasswords struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
	Edges struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
		SourceNode struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			Options struct {
				field.RelationField
				Question struct {
					field.RelationField
				}
			}
			OutgoingEdges struct {
				field.RelationField
			}
			IncomingEdges struct {
				field.RelationField
			}
		}
		TargetNode struct {
			field.RelationField
		}
	}
	Questions struct {
		field.RelationField
	}
	Responses struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
}

func (a edgeBelongsToForm) Where(conds ...field.Expr) *edgeBelongsToForm {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a edgeBelongsToForm) WithContext(ctx context.Context) *edgeBelongsToForm {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a edgeBelongsToForm) Session(session *gorm.Session) *edgeBelongsToForm {
	a.db = a.db.Session(session)
	return &a
}

func (a edgeBelongsToForm) Model(m *models.Edge) *edgeBelongsToFormTx {
	return &edgeBelongsToFormTx{a.db.Model(m).Association(a.Name())}
}

func (a edgeBelongsToForm) Unscoped() *edgeBelongsToForm {
	a.db = a.db.Unscoped()
	return &a
}

type edgeBelongsToFormTx struct{ tx *gorm.Association }

func (a edgeBelongsToFormTx) Find() (result *models.Form, err error) {
	return result, a.tx.Find(&result)
}

func (a edgeBelongsToFormTx) Append(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a edgeBelongsToFormTx) Replace(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a edgeBelongsToFormTx) Delete(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a edgeBelongsToFormTx) Clear() error {
	return a.tx.Clear()
}

func (a edgeBelongsToFormTx) Count() int64 {
	return a.tx.Count()
}

func (a edgeBelongsToFormTx) Unscoped() *edgeBelongsToFormTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type edgeBelongsToSourceNode struct {
	db *gorm.DB

	field.RelationField
}

func (a edgeBelongsToSourceNode) Where(conds ...field.Expr) *edgeBelongsToSourceNode {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a edgeBelongsToSourceNode) WithContext(ctx context.Context) *edgeBelongsToSourceNode {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a edgeBelongsToSourceNode) Session(session *gorm.Session) *edgeBelongsToSourceNode {
	a.db = a.db.Session(session)
	return &a
}

func (a edgeBelongsToSourceNode) Model(m *models.Edge) *edgeBelongsToSourceNodeTx {
	return &edgeBelongsToSourceNodeTx{a.db.Model(m).Association(a.Name())}
}

func (a edgeBelongsToSourceNode) Unscoped() *edgeBelongsToSourceNode {
	a.db = a.db.Unscoped()
	return &a
}

type edgeBelongsToSourceNodeTx struct{ tx *gorm.Association }

func (a edgeBelongsToSourceNodeTx) Find() (result *models.Question, err error) {
	return result, a.tx.Find(&result)
}

func (a edgeBelongsToSourceNodeTx) Append(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a edgeBelongsToSourceNodeTx) Replace(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a edgeBelongsToSourceNodeTx) Delete(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a edgeBelongsToSourceNodeTx) Clear() error {
	return a.tx.Clear()
}

func (a edgeBelongsToSourceNodeTx) Count() int64 {
	return a.tx.Count()
}

func (a edgeBelongsToSourceNodeTx) Unscoped() *edgeBelongsToSourceNodeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type edgeBelongsToTargetNode struct {
	db *gorm.DB

	field.RelationField
}

func (a edgeBelongsToTargetNode) Where(conds ...field.Expr) *edgeBelongsToTargetNode {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a edgeBelongsToTargetNode) WithContext(ctx context.Context) *edgeBelongsToTargetNode {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a edgeBelongsToTargetNode) Session(session *gorm.Session) *edgeBelongsToTargetNode {
	a.db = a.db.Session(session)
	return &a
}

func (a edgeBelongsToTargetNode) Model(m *models.Edge) *edgeBelongsToTargetNodeTx {
	return &edgeBelongsToTargetNodeTx{a.db.Model(m).Association(a.Name())}
}

func (a edgeBelongsToTargetNode) Unscoped() *edgeBelongsToTargetNode {
	a.db = a.db.Unscoped()
	return &a
}

type edgeBelongsToTargetNodeTx struct{ tx *gorm.Association }

func (a edgeBelongsToTargetNodeTx) Find() (result *models.Question, err error) {
	return result, a.tx.Find(&result)
}

func (a edgeBelongsToTargetNodeTx) Append(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a edgeBelongsToTargetNodeTx) Replace(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a edgeBelongsToTargetNodeTx) Delete(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a edgeBelongsToTargetNodeTx) Clear() error {
	return a.tx.Clear()
}

func (a edgeBelongsToTargetNodeTx) Count() int64 {
	return a.tx.Count()
}

func (a edgeBelongsToTargetNodeTx) Unscoped() *edgeBelongsToTargetNodeTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type edgeDo struct{ gen.DO }

type IEdgeDo interface {
	gen.SubQuery
	Debug() IEdgeDo
	WithContext(ctx context.Context) IEdgeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEdgeDo
	WriteDB() IEdgeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEdgeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEdgeDo
	Not(conds ...gen.Condition) IEdgeDo
	Or(conds ...gen.Condition) IEdgeDo
	Select(conds ...field.Expr) IEdgeDo
	Where(conds ...gen.Condition) IEdgeDo
	Order(conds ...field.Expr) IEdgeDo
	Distinct(cols ...field.Expr) IEdgeDo
	Omit(cols ...field.Expr) IEdgeDo
	Join(table schema.Tabler, on ...field.Expr) IEdgeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEdgeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEdgeDo
	Group(cols ...field.Expr) IEdgeDo
	Having(conds ...gen.Condition) IEdgeDo
	Limit(limit int) IEdgeDo
	Offset(offset int) IEdgeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEdgeDo
	Unscoped() IEdgeDo
	Create(values ...*models.Edge) error
	CreateInBatches(values []*models.Edge, batchSize int) error
	Save(values ...*models.Edge) error
	First() (*models.Edge, error)
	Take() (*models.Edge, error)
	Last() (*models.Edge, error)
	Find() ([]*models.Edge, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Edge, err error)
	FindInBatches(result *[]*models.Edge, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Edge) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEdgeDo
	Assign(attrs ...field.AssignExpr) IEdgeDo
	Joins(fields ...field.RelationField) IEdgeDo
	Preload(fields ...field.RelationField) IEdgeDo
	FirstOrInit() (*models.Edge, error)
	FirstOrCreate() (*models.Edge, error)
	FindByPage(offset int, limit int) (result []*models.Edge, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEdgeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e edgeDo) Debug() IEdgeDo {
	return e.withDO(e.DO.Debug())
}

func (e edgeDo) WithContext(ctx context.Context) IEdgeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e edgeDo) ReadDB() IEdgeDo {
	return e.Clauses(dbresolver.Read)
}

func (e edgeDo) WriteDB() IEdgeDo {
	return e.Clauses(dbresolver.Write)
}

func (e edgeDo) Session(config *gorm.Session) IEdgeDo {
	return e.withDO(e.DO.Session(config))
}

func (e edgeDo) Clauses(conds ...clause.Expression) IEdgeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e edgeDo) Returning(value interface{}, columns ...string) IEdgeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e edgeDo) Not(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e edgeDo) Or(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e edgeDo) Select(conds ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e edgeDo) Where(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e edgeDo) Order(conds ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e edgeDo) Distinct(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e edgeDo) Omit(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e edgeDo) Join(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e edgeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e edgeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e edgeDo) Group(cols ...field.Expr) IEdgeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e edgeDo) Having(conds ...gen.Condition) IEdgeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e edgeDo) Limit(limit int) IEdgeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e edgeDo) Offset(offset int) IEdgeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e edgeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEdgeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e edgeDo) Unscoped() IEdgeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e edgeDo) Create(values ...*models.Edge) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e edgeDo) CreateInBatches(values []*models.Edge, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e edgeDo) Save(values ...*models.Edge) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e edgeDo) First() (*models.Edge, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Edge), nil
	}
}

func (e edgeDo) Take() (*models.Edge, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Edge), nil
	}
}

func (e edgeDo) Last() (*models.Edge, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Edge), nil
	}
}

func (e edgeDo) Find() ([]*models.Edge, error) {
	result, err := e.DO.Find()
	return result.([]*models.Edge), err
}

func (e edgeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Edge, err error) {
	buf := make([]*models.Edge, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e edgeDo) FindInBatches(result *[]*models.Edge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e edgeDo) Attrs(attrs ...field.AssignExpr) IEdgeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e edgeDo) Assign(attrs ...field.AssignExpr) IEdgeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e edgeDo) Joins(fields ...field.RelationField) IEdgeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e edgeDo) Preload(fields ...field.RelationField) IEdgeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e edgeDo) FirstOrInit() (*models.Edge, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Edge), nil
	}
}

func (e edgeDo) FirstOrCreate() (*models.Edge, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Edge), nil
	}
}

func (e edgeDo) FindByPage(offset int, limit int) (result []*models.Edge, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e edgeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e edgeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e edgeDo) Delete(models ...*models.Edge) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *edgeDo) withDO(do gen.Dao) *edgeDo {
	e.DO = *do.(*gen.DO)
	return e
}
