// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newFeature(db *gorm.DB, opts ...gen.DOOption) feature {
	_feature := feature{}

	_feature.featureDo.UseDB(db, opts...)
	_feature.featureDo.UseModel(&models.Feature{})

	tableName := _feature.featureDo.TableName()
	_feature.ALL = field.NewAsterisk(tableName)
	_feature.ID = field.NewString(tableName, "id")
	_feature.PlanID = field.NewString(tableName, "planId")
	_feature.Key = field.NewString(tableName, "key")
	_feature.Name = field.NewString(tableName, "name")
	_feature.Description = field.NewString(tableName, "description")
	_feature.Valid = field.NewBool(tableName, "valid")
	_feature.CreatedAt = field.NewTime(tableName, "createdAt")
	_feature.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_feature.Plan = featureBelongsToPlan{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Plan", "models.Plan"),
		Coupons: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Plan.Coupons", "models.Coupon"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Coupons.Plan", "models.Plan"),
			},
		},
		Features: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Plan.Features", "models.Feature"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Features.Plan", "models.Plan"),
			},
		},
		Teams: struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
			Forms struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}
			Projects struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Plan.Teams", "models.Team"),
			Plan: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Teams.Plan", "models.Plan"),
			},
			Forms: struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Plan.Teams.Forms", "models.Form"),
				Project: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Project", "models.Project"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Project.Team", "models.Team"),
					},
					Forms: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Project.Forms", "models.Form"),
					},
				},
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Team", "models.Team"),
				},
				ActivePasswords: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.ActivePasswords", "models.ActivePassword"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.ActivePasswords.Form", "models.Form"),
					},
				},
				Edges: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Edges", "models.Edge"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.Form", "models.Form"),
					},
					SourceNode: struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode", "models.Question"),
						Form: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Form", "models.Form"),
						},
						Options: struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Options", "models.QuestionOption"),
							Question: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.Options.Question", "models.Question"),
							},
						},
						OutgoingEdges: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
						},
						IncomingEdges: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Plan.Teams.Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
						},
					},
					TargetNode: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Edges.TargetNode", "models.Question"),
					},
				},
				Questions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Questions", "models.Question"),
				},
				Responses: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Plan.Teams.Forms.Responses", "models.Response"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Plan.Teams.Forms.Responses.Form", "models.Form"),
					},
				},
			},
			Projects: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Plan.Teams.Projects", "models.Project"),
			},
		},
	}

	_feature.fillFieldMap()

	return _feature
}

type feature struct {
	featureDo

	ALL         field.Asterisk
	ID          field.String
	PlanID      field.String
	Key         field.String
	Name        field.String
	Description field.String
	Valid       field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Plan        featureBelongsToPlan

	fieldMap map[string]field.Expr
}

func (f feature) Table(newTableName string) *feature {
	f.featureDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f feature) As(alias string) *feature {
	f.featureDo.DO = *(f.featureDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *feature) updateTableName(table string) *feature {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.PlanID = field.NewString(table, "planId")
	f.Key = field.NewString(table, "key")
	f.Name = field.NewString(table, "name")
	f.Description = field.NewString(table, "description")
	f.Valid = field.NewBool(table, "valid")
	f.CreatedAt = field.NewTime(table, "createdAt")
	f.UpdatedAt = field.NewTime(table, "updatedAt")

	f.fillFieldMap()

	return f
}

func (f *feature) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *feature) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 9)
	f.fieldMap["id"] = f.ID
	f.fieldMap["planId"] = f.PlanID
	f.fieldMap["key"] = f.Key
	f.fieldMap["name"] = f.Name
	f.fieldMap["description"] = f.Description
	f.fieldMap["valid"] = f.Valid
	f.fieldMap["createdAt"] = f.CreatedAt
	f.fieldMap["updatedAt"] = f.UpdatedAt

}

func (f feature) clone(db *gorm.DB) feature {
	f.featureDo.ReplaceConnPool(db.Statement.ConnPool)
	f.Plan.db = db.Session(&gorm.Session{Initialized: true})
	f.Plan.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f feature) replaceDB(db *gorm.DB) feature {
	f.featureDo.ReplaceDB(db)
	f.Plan.db = db.Session(&gorm.Session{})
	return f
}

type featureBelongsToPlan struct {
	db *gorm.DB

	field.RelationField

	Coupons struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
	}
	Features struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
	}
	Teams struct {
		field.RelationField
		Plan struct {
			field.RelationField
		}
		Forms struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}
		Projects struct {
			field.RelationField
		}
	}
}

func (a featureBelongsToPlan) Where(conds ...field.Expr) *featureBelongsToPlan {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a featureBelongsToPlan) WithContext(ctx context.Context) *featureBelongsToPlan {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a featureBelongsToPlan) Session(session *gorm.Session) *featureBelongsToPlan {
	a.db = a.db.Session(session)
	return &a
}

func (a featureBelongsToPlan) Model(m *models.Feature) *featureBelongsToPlanTx {
	return &featureBelongsToPlanTx{a.db.Model(m).Association(a.Name())}
}

func (a featureBelongsToPlan) Unscoped() *featureBelongsToPlan {
	a.db = a.db.Unscoped()
	return &a
}

type featureBelongsToPlanTx struct{ tx *gorm.Association }

func (a featureBelongsToPlanTx) Find() (result *models.Plan, err error) {
	return result, a.tx.Find(&result)
}

func (a featureBelongsToPlanTx) Append(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a featureBelongsToPlanTx) Replace(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a featureBelongsToPlanTx) Delete(values ...*models.Plan) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a featureBelongsToPlanTx) Clear() error {
	return a.tx.Clear()
}

func (a featureBelongsToPlanTx) Count() int64 {
	return a.tx.Count()
}

func (a featureBelongsToPlanTx) Unscoped() *featureBelongsToPlanTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type featureDo struct{ gen.DO }

type IFeatureDo interface {
	gen.SubQuery
	Debug() IFeatureDo
	WithContext(ctx context.Context) IFeatureDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFeatureDo
	WriteDB() IFeatureDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFeatureDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFeatureDo
	Not(conds ...gen.Condition) IFeatureDo
	Or(conds ...gen.Condition) IFeatureDo
	Select(conds ...field.Expr) IFeatureDo
	Where(conds ...gen.Condition) IFeatureDo
	Order(conds ...field.Expr) IFeatureDo
	Distinct(cols ...field.Expr) IFeatureDo
	Omit(cols ...field.Expr) IFeatureDo
	Join(table schema.Tabler, on ...field.Expr) IFeatureDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFeatureDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFeatureDo
	Group(cols ...field.Expr) IFeatureDo
	Having(conds ...gen.Condition) IFeatureDo
	Limit(limit int) IFeatureDo
	Offset(offset int) IFeatureDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFeatureDo
	Unscoped() IFeatureDo
	Create(values ...*models.Feature) error
	CreateInBatches(values []*models.Feature, batchSize int) error
	Save(values ...*models.Feature) error
	First() (*models.Feature, error)
	Take() (*models.Feature, error)
	Last() (*models.Feature, error)
	Find() ([]*models.Feature, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Feature, err error)
	FindInBatches(result *[]*models.Feature, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Feature) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFeatureDo
	Assign(attrs ...field.AssignExpr) IFeatureDo
	Joins(fields ...field.RelationField) IFeatureDo
	Preload(fields ...field.RelationField) IFeatureDo
	FirstOrInit() (*models.Feature, error)
	FirstOrCreate() (*models.Feature, error)
	FindByPage(offset int, limit int) (result []*models.Feature, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFeatureDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f featureDo) Debug() IFeatureDo {
	return f.withDO(f.DO.Debug())
}

func (f featureDo) WithContext(ctx context.Context) IFeatureDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f featureDo) ReadDB() IFeatureDo {
	return f.Clauses(dbresolver.Read)
}

func (f featureDo) WriteDB() IFeatureDo {
	return f.Clauses(dbresolver.Write)
}

func (f featureDo) Session(config *gorm.Session) IFeatureDo {
	return f.withDO(f.DO.Session(config))
}

func (f featureDo) Clauses(conds ...clause.Expression) IFeatureDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f featureDo) Returning(value interface{}, columns ...string) IFeatureDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f featureDo) Not(conds ...gen.Condition) IFeatureDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f featureDo) Or(conds ...gen.Condition) IFeatureDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f featureDo) Select(conds ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f featureDo) Where(conds ...gen.Condition) IFeatureDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f featureDo) Order(conds ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f featureDo) Distinct(cols ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f featureDo) Omit(cols ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f featureDo) Join(table schema.Tabler, on ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f featureDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f featureDo) RightJoin(table schema.Tabler, on ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f featureDo) Group(cols ...field.Expr) IFeatureDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f featureDo) Having(conds ...gen.Condition) IFeatureDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f featureDo) Limit(limit int) IFeatureDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f featureDo) Offset(offset int) IFeatureDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f featureDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFeatureDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f featureDo) Unscoped() IFeatureDo {
	return f.withDO(f.DO.Unscoped())
}

func (f featureDo) Create(values ...*models.Feature) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f featureDo) CreateInBatches(values []*models.Feature, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f featureDo) Save(values ...*models.Feature) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f featureDo) First() (*models.Feature, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Feature), nil
	}
}

func (f featureDo) Take() (*models.Feature, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Feature), nil
	}
}

func (f featureDo) Last() (*models.Feature, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Feature), nil
	}
}

func (f featureDo) Find() ([]*models.Feature, error) {
	result, err := f.DO.Find()
	return result.([]*models.Feature), err
}

func (f featureDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Feature, err error) {
	buf := make([]*models.Feature, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f featureDo) FindInBatches(result *[]*models.Feature, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f featureDo) Attrs(attrs ...field.AssignExpr) IFeatureDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f featureDo) Assign(attrs ...field.AssignExpr) IFeatureDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f featureDo) Joins(fields ...field.RelationField) IFeatureDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f featureDo) Preload(fields ...field.RelationField) IFeatureDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f featureDo) FirstOrInit() (*models.Feature, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Feature), nil
	}
}

func (f featureDo) FirstOrCreate() (*models.Feature, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Feature), nil
	}
}

func (f featureDo) FindByPage(offset int, limit int) (result []*models.Feature, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f featureDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f featureDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f featureDo) Delete(models ...*models.Feature) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *featureDo) withDO(do gen.Dao) *featureDo {
	f.DO = *do.(*gen.DO)
	return f
}
