// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newForm(db *gorm.DB, opts ...gen.DOOption) form {
	_form := form{}

	_form.formDo.UseDB(db, opts...)
	_form.formDo.UseModel(&models.Form{})

	tableName := _form.formDo.TableName()
	_form.ALL = field.NewAsterisk(tableName)
	_form.ID = field.NewString(tableName, "id")
	_form.Name = field.NewString(tableName, "name")
	_form.Description = field.NewString(tableName, "description")
	_form.TeamID = field.NewString(tableName, "team_id")
	_form.ProjectID = field.NewString(tableName, "project_id")
	_form.Theme = field.NewString(tableName, "theme")
	_form.LogoURL = field.NewString(tableName, "logo_url")
	_form.MaxResponses = field.NewInt(tableName, "max_responses")
	_form.OpenAt = field.NewTime(tableName, "open_at")
	_form.CloseAt = field.NewTime(tableName, "close_at")
	_form.Status = field.NewString(tableName, "status")
	_form.UniqueSubdomain = field.NewString(tableName, "unique_subdomain")
	_form.CustomDomain = field.NewString(tableName, "custom_domain")
	_form.RequireConsent = field.NewBool(tableName, "require_consent")
	_form.AllowAnonymous = field.NewBool(tableName, "allow_anonymous")
	_form.MultipleSubmissions = field.NewBool(tableName, "multiple_submissions")
	_form.PasswordProtected = field.NewBool(tableName, "password_protected")
	_form.AnalyticsEnabled = field.NewBool(tableName, "analytics_enabled")
	_form.Valid = field.NewBool(tableName, "valid")
	_form.Metadata = field.NewString(tableName, "metadata")
	_form.CreatedBy = field.NewString(tableName, "created_by")
	_form.CreatedAt = field.NewTime(tableName, "created_at")
	_form.UpdatedAt = field.NewTime(tableName, "updated_at")
	_form.FormPageType = field.NewString(tableName, "form_page_type")
	_form.ActivePasswords = formHasManyActivePasswords{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ActivePasswords", "models.ActivePassword"),
		Form: struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
					Transactions struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("ActivePasswords.Form", "models.Form"),
			Project: struct {
				field.RelationField
				Team struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
					Transactions struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
				}
				Forms struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.Project", "models.Project"),
				Team: struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
					Transactions struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Project.Team", "models.Team"),
					Plan: struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan", "models.Plan"),
						Coupons: struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan.Coupons", "models.Coupon"),
							Plan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
							},
						},
						Features: struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan.Features", "models.Feature"),
							Plan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan.Features.Plan", "models.Plan"),
							},
						},
						Teams: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Plan.Teams", "models.Team"),
						},
					},
					Forms: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Forms", "models.Form"),
					},
					Projects: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Projects", "models.Project"),
					},
					Transactions: struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Transactions", "models.Transaction"),
						Team: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ActivePasswords.Form.Project.Team.Transactions.Team", "models.Team"),
						},
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Project.Forms", "models.Form"),
				},
			},
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.Team", "models.Team"),
			},
			ActivePasswords: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.ActivePasswords", "models.ActivePassword"),
			},
			Edges: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.Edges", "models.Edge"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Edges.Form", "models.Form"),
				},
				SourceNode: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode", "models.Question"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode.Form", "models.Form"),
					},
					Options: struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode.Options", "models.QuestionOption"),
						Question: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode.Options.Question", "models.Question"),
						},
					},
					OutgoingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode.OutgoingEdges", "models.Edge"),
					},
					IncomingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("ActivePasswords.Form.Edges.SourceNode.IncomingEdges", "models.Edge"),
					},
				},
				TargetNode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Edges.TargetNode", "models.Question"),
				},
			},
			Questions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.Questions", "models.Question"),
			},
			Responses: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("ActivePasswords.Form.Responses", "models.Response"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("ActivePasswords.Form.Responses.Form", "models.Form"),
				},
			},
		},
	}

	_form.Edges = formHasManyEdges{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Edges", "models.Edge"),
	}

	_form.Questions = formHasManyQuestions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Questions", "models.Question"),
	}

	_form.Responses = formHasManyResponses{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Responses", "models.Response"),
	}

	_form.Project = formBelongsToProject{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Project", "models.Project"),
	}

	_form.Team = formBelongsToTeam{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Team", "models.Team"),
	}

	_form.fillFieldMap()

	return _form
}

type form struct {
	formDo

	ALL                 field.Asterisk
	ID                  field.String
	Name                field.String
	Description         field.String
	TeamID              field.String
	ProjectID           field.String
	Theme               field.String
	LogoURL             field.String
	MaxResponses        field.Int
	OpenAt              field.Time
	CloseAt             field.Time
	Status              field.String
	UniqueSubdomain     field.String
	CustomDomain        field.String
	RequireConsent      field.Bool
	AllowAnonymous      field.Bool
	MultipleSubmissions field.Bool
	PasswordProtected   field.Bool
	AnalyticsEnabled    field.Bool
	Valid               field.Bool
	Metadata            field.String
	CreatedBy           field.String
	CreatedAt           field.Time
	UpdatedAt           field.Time
	FormPageType        field.String
	ActivePasswords     formHasManyActivePasswords

	Edges formHasManyEdges

	Questions formHasManyQuestions

	Responses formHasManyResponses

	Project formBelongsToProject

	Team formBelongsToTeam

	fieldMap map[string]field.Expr
}

func (f form) Table(newTableName string) *form {
	f.formDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f form) As(alias string) *form {
	f.formDo.DO = *(f.formDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *form) updateTableName(table string) *form {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.Name = field.NewString(table, "name")
	f.Description = field.NewString(table, "description")
	f.TeamID = field.NewString(table, "team_id")
	f.ProjectID = field.NewString(table, "project_id")
	f.Theme = field.NewString(table, "theme")
	f.LogoURL = field.NewString(table, "logo_url")
	f.MaxResponses = field.NewInt(table, "max_responses")
	f.OpenAt = field.NewTime(table, "open_at")
	f.CloseAt = field.NewTime(table, "close_at")
	f.Status = field.NewString(table, "status")
	f.UniqueSubdomain = field.NewString(table, "unique_subdomain")
	f.CustomDomain = field.NewString(table, "custom_domain")
	f.RequireConsent = field.NewBool(table, "require_consent")
	f.AllowAnonymous = field.NewBool(table, "allow_anonymous")
	f.MultipleSubmissions = field.NewBool(table, "multiple_submissions")
	f.PasswordProtected = field.NewBool(table, "password_protected")
	f.AnalyticsEnabled = field.NewBool(table, "analytics_enabled")
	f.Valid = field.NewBool(table, "valid")
	f.Metadata = field.NewString(table, "metadata")
	f.CreatedBy = field.NewString(table, "created_by")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")
	f.FormPageType = field.NewString(table, "form_page_type")

	f.fillFieldMap()

	return f
}

func (f *form) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *form) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 30)
	f.fieldMap["id"] = f.ID
	f.fieldMap["name"] = f.Name
	f.fieldMap["description"] = f.Description
	f.fieldMap["team_id"] = f.TeamID
	f.fieldMap["project_id"] = f.ProjectID
	f.fieldMap["theme"] = f.Theme
	f.fieldMap["logo_url"] = f.LogoURL
	f.fieldMap["max_responses"] = f.MaxResponses
	f.fieldMap["open_at"] = f.OpenAt
	f.fieldMap["close_at"] = f.CloseAt
	f.fieldMap["status"] = f.Status
	f.fieldMap["unique_subdomain"] = f.UniqueSubdomain
	f.fieldMap["custom_domain"] = f.CustomDomain
	f.fieldMap["require_consent"] = f.RequireConsent
	f.fieldMap["allow_anonymous"] = f.AllowAnonymous
	f.fieldMap["multiple_submissions"] = f.MultipleSubmissions
	f.fieldMap["password_protected"] = f.PasswordProtected
	f.fieldMap["analytics_enabled"] = f.AnalyticsEnabled
	f.fieldMap["valid"] = f.Valid
	f.fieldMap["metadata"] = f.Metadata
	f.fieldMap["created_by"] = f.CreatedBy
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
	f.fieldMap["form_page_type"] = f.FormPageType

}

func (f form) clone(db *gorm.DB) form {
	f.formDo.ReplaceConnPool(db.Statement.ConnPool)
	f.ActivePasswords.db = db.Session(&gorm.Session{Initialized: true})
	f.ActivePasswords.db.Statement.ConnPool = db.Statement.ConnPool
	f.Edges.db = db.Session(&gorm.Session{Initialized: true})
	f.Edges.db.Statement.ConnPool = db.Statement.ConnPool
	f.Questions.db = db.Session(&gorm.Session{Initialized: true})
	f.Questions.db.Statement.ConnPool = db.Statement.ConnPool
	f.Responses.db = db.Session(&gorm.Session{Initialized: true})
	f.Responses.db.Statement.ConnPool = db.Statement.ConnPool
	f.Project.db = db.Session(&gorm.Session{Initialized: true})
	f.Project.db.Statement.ConnPool = db.Statement.ConnPool
	f.Team.db = db.Session(&gorm.Session{Initialized: true})
	f.Team.db.Statement.ConnPool = db.Statement.ConnPool
	return f
}

func (f form) replaceDB(db *gorm.DB) form {
	f.formDo.ReplaceDB(db)
	f.ActivePasswords.db = db.Session(&gorm.Session{})
	f.Edges.db = db.Session(&gorm.Session{})
	f.Questions.db = db.Session(&gorm.Session{})
	f.Responses.db = db.Session(&gorm.Session{})
	f.Project.db = db.Session(&gorm.Session{})
	f.Team.db = db.Session(&gorm.Session{})
	return f
}

type formHasManyActivePasswords struct {
	db *gorm.DB

	field.RelationField

	Form struct {
		field.RelationField
		Project struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}
			Forms struct {
				field.RelationField
			}
		}
		Team struct {
			field.RelationField
		}
		ActivePasswords struct {
			field.RelationField
		}
		Edges struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}
		Questions struct {
			field.RelationField
		}
		Responses struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
	}
}

func (a formHasManyActivePasswords) Where(conds ...field.Expr) *formHasManyActivePasswords {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formHasManyActivePasswords) WithContext(ctx context.Context) *formHasManyActivePasswords {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formHasManyActivePasswords) Session(session *gorm.Session) *formHasManyActivePasswords {
	a.db = a.db.Session(session)
	return &a
}

func (a formHasManyActivePasswords) Model(m *models.Form) *formHasManyActivePasswordsTx {
	return &formHasManyActivePasswordsTx{a.db.Model(m).Association(a.Name())}
}

func (a formHasManyActivePasswords) Unscoped() *formHasManyActivePasswords {
	a.db = a.db.Unscoped()
	return &a
}

type formHasManyActivePasswordsTx struct{ tx *gorm.Association }

func (a formHasManyActivePasswordsTx) Find() (result []*models.ActivePassword, err error) {
	return result, a.tx.Find(&result)
}

func (a formHasManyActivePasswordsTx) Append(values ...*models.ActivePassword) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formHasManyActivePasswordsTx) Replace(values ...*models.ActivePassword) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formHasManyActivePasswordsTx) Delete(values ...*models.ActivePassword) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formHasManyActivePasswordsTx) Clear() error {
	return a.tx.Clear()
}

func (a formHasManyActivePasswordsTx) Count() int64 {
	return a.tx.Count()
}

func (a formHasManyActivePasswordsTx) Unscoped() *formHasManyActivePasswordsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formHasManyEdges struct {
	db *gorm.DB

	field.RelationField
}

func (a formHasManyEdges) Where(conds ...field.Expr) *formHasManyEdges {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formHasManyEdges) WithContext(ctx context.Context) *formHasManyEdges {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formHasManyEdges) Session(session *gorm.Session) *formHasManyEdges {
	a.db = a.db.Session(session)
	return &a
}

func (a formHasManyEdges) Model(m *models.Form) *formHasManyEdgesTx {
	return &formHasManyEdgesTx{a.db.Model(m).Association(a.Name())}
}

func (a formHasManyEdges) Unscoped() *formHasManyEdges {
	a.db = a.db.Unscoped()
	return &a
}

type formHasManyEdgesTx struct{ tx *gorm.Association }

func (a formHasManyEdgesTx) Find() (result []*models.Edge, err error) {
	return result, a.tx.Find(&result)
}

func (a formHasManyEdgesTx) Append(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formHasManyEdgesTx) Replace(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formHasManyEdgesTx) Delete(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formHasManyEdgesTx) Clear() error {
	return a.tx.Clear()
}

func (a formHasManyEdgesTx) Count() int64 {
	return a.tx.Count()
}

func (a formHasManyEdgesTx) Unscoped() *formHasManyEdgesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formHasManyQuestions struct {
	db *gorm.DB

	field.RelationField
}

func (a formHasManyQuestions) Where(conds ...field.Expr) *formHasManyQuestions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formHasManyQuestions) WithContext(ctx context.Context) *formHasManyQuestions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formHasManyQuestions) Session(session *gorm.Session) *formHasManyQuestions {
	a.db = a.db.Session(session)
	return &a
}

func (a formHasManyQuestions) Model(m *models.Form) *formHasManyQuestionsTx {
	return &formHasManyQuestionsTx{a.db.Model(m).Association(a.Name())}
}

func (a formHasManyQuestions) Unscoped() *formHasManyQuestions {
	a.db = a.db.Unscoped()
	return &a
}

type formHasManyQuestionsTx struct{ tx *gorm.Association }

func (a formHasManyQuestionsTx) Find() (result []*models.Question, err error) {
	return result, a.tx.Find(&result)
}

func (a formHasManyQuestionsTx) Append(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formHasManyQuestionsTx) Replace(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formHasManyQuestionsTx) Delete(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formHasManyQuestionsTx) Clear() error {
	return a.tx.Clear()
}

func (a formHasManyQuestionsTx) Count() int64 {
	return a.tx.Count()
}

func (a formHasManyQuestionsTx) Unscoped() *formHasManyQuestionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formHasManyResponses struct {
	db *gorm.DB

	field.RelationField
}

func (a formHasManyResponses) Where(conds ...field.Expr) *formHasManyResponses {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formHasManyResponses) WithContext(ctx context.Context) *formHasManyResponses {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formHasManyResponses) Session(session *gorm.Session) *formHasManyResponses {
	a.db = a.db.Session(session)
	return &a
}

func (a formHasManyResponses) Model(m *models.Form) *formHasManyResponsesTx {
	return &formHasManyResponsesTx{a.db.Model(m).Association(a.Name())}
}

func (a formHasManyResponses) Unscoped() *formHasManyResponses {
	a.db = a.db.Unscoped()
	return &a
}

type formHasManyResponsesTx struct{ tx *gorm.Association }

func (a formHasManyResponsesTx) Find() (result []*models.Response, err error) {
	return result, a.tx.Find(&result)
}

func (a formHasManyResponsesTx) Append(values ...*models.Response) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formHasManyResponsesTx) Replace(values ...*models.Response) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formHasManyResponsesTx) Delete(values ...*models.Response) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formHasManyResponsesTx) Clear() error {
	return a.tx.Clear()
}

func (a formHasManyResponsesTx) Count() int64 {
	return a.tx.Count()
}

func (a formHasManyResponsesTx) Unscoped() *formHasManyResponsesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formBelongsToProject struct {
	db *gorm.DB

	field.RelationField
}

func (a formBelongsToProject) Where(conds ...field.Expr) *formBelongsToProject {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formBelongsToProject) WithContext(ctx context.Context) *formBelongsToProject {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formBelongsToProject) Session(session *gorm.Session) *formBelongsToProject {
	a.db = a.db.Session(session)
	return &a
}

func (a formBelongsToProject) Model(m *models.Form) *formBelongsToProjectTx {
	return &formBelongsToProjectTx{a.db.Model(m).Association(a.Name())}
}

func (a formBelongsToProject) Unscoped() *formBelongsToProject {
	a.db = a.db.Unscoped()
	return &a
}

type formBelongsToProjectTx struct{ tx *gorm.Association }

func (a formBelongsToProjectTx) Find() (result *models.Project, err error) {
	return result, a.tx.Find(&result)
}

func (a formBelongsToProjectTx) Append(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formBelongsToProjectTx) Replace(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formBelongsToProjectTx) Delete(values ...*models.Project) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formBelongsToProjectTx) Clear() error {
	return a.tx.Clear()
}

func (a formBelongsToProjectTx) Count() int64 {
	return a.tx.Count()
}

func (a formBelongsToProjectTx) Unscoped() *formBelongsToProjectTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formBelongsToTeam struct {
	db *gorm.DB

	field.RelationField
}

func (a formBelongsToTeam) Where(conds ...field.Expr) *formBelongsToTeam {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a formBelongsToTeam) WithContext(ctx context.Context) *formBelongsToTeam {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a formBelongsToTeam) Session(session *gorm.Session) *formBelongsToTeam {
	a.db = a.db.Session(session)
	return &a
}

func (a formBelongsToTeam) Model(m *models.Form) *formBelongsToTeamTx {
	return &formBelongsToTeamTx{a.db.Model(m).Association(a.Name())}
}

func (a formBelongsToTeam) Unscoped() *formBelongsToTeam {
	a.db = a.db.Unscoped()
	return &a
}

type formBelongsToTeamTx struct{ tx *gorm.Association }

func (a formBelongsToTeamTx) Find() (result *models.Team, err error) {
	return result, a.tx.Find(&result)
}

func (a formBelongsToTeamTx) Append(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a formBelongsToTeamTx) Replace(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a formBelongsToTeamTx) Delete(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a formBelongsToTeamTx) Clear() error {
	return a.tx.Clear()
}

func (a formBelongsToTeamTx) Count() int64 {
	return a.tx.Count()
}

func (a formBelongsToTeamTx) Unscoped() *formBelongsToTeamTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type formDo struct{ gen.DO }

type IFormDo interface {
	gen.SubQuery
	Debug() IFormDo
	WithContext(ctx context.Context) IFormDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFormDo
	WriteDB() IFormDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFormDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFormDo
	Not(conds ...gen.Condition) IFormDo
	Or(conds ...gen.Condition) IFormDo
	Select(conds ...field.Expr) IFormDo
	Where(conds ...gen.Condition) IFormDo
	Order(conds ...field.Expr) IFormDo
	Distinct(cols ...field.Expr) IFormDo
	Omit(cols ...field.Expr) IFormDo
	Join(table schema.Tabler, on ...field.Expr) IFormDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFormDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFormDo
	Group(cols ...field.Expr) IFormDo
	Having(conds ...gen.Condition) IFormDo
	Limit(limit int) IFormDo
	Offset(offset int) IFormDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFormDo
	Unscoped() IFormDo
	Create(values ...*models.Form) error
	CreateInBatches(values []*models.Form, batchSize int) error
	Save(values ...*models.Form) error
	First() (*models.Form, error)
	Take() (*models.Form, error)
	Last() (*models.Form, error)
	Find() ([]*models.Form, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Form, err error)
	FindInBatches(result *[]*models.Form, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Form) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFormDo
	Assign(attrs ...field.AssignExpr) IFormDo
	Joins(fields ...field.RelationField) IFormDo
	Preload(fields ...field.RelationField) IFormDo
	FirstOrInit() (*models.Form, error)
	FirstOrCreate() (*models.Form, error)
	FindByPage(offset int, limit int) (result []*models.Form, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFormDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f formDo) Debug() IFormDo {
	return f.withDO(f.DO.Debug())
}

func (f formDo) WithContext(ctx context.Context) IFormDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f formDo) ReadDB() IFormDo {
	return f.Clauses(dbresolver.Read)
}

func (f formDo) WriteDB() IFormDo {
	return f.Clauses(dbresolver.Write)
}

func (f formDo) Session(config *gorm.Session) IFormDo {
	return f.withDO(f.DO.Session(config))
}

func (f formDo) Clauses(conds ...clause.Expression) IFormDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f formDo) Returning(value interface{}, columns ...string) IFormDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f formDo) Not(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f formDo) Or(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f formDo) Select(conds ...field.Expr) IFormDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f formDo) Where(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f formDo) Order(conds ...field.Expr) IFormDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f formDo) Distinct(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f formDo) Omit(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f formDo) Join(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f formDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f formDo) RightJoin(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f formDo) Group(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f formDo) Having(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f formDo) Limit(limit int) IFormDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f formDo) Offset(offset int) IFormDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f formDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFormDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f formDo) Unscoped() IFormDo {
	return f.withDO(f.DO.Unscoped())
}

func (f formDo) Create(values ...*models.Form) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f formDo) CreateInBatches(values []*models.Form, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f formDo) Save(values ...*models.Form) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f formDo) First() (*models.Form, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Form), nil
	}
}

func (f formDo) Take() (*models.Form, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Form), nil
	}
}

func (f formDo) Last() (*models.Form, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Form), nil
	}
}

func (f formDo) Find() ([]*models.Form, error) {
	result, err := f.DO.Find()
	return result.([]*models.Form), err
}

func (f formDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Form, err error) {
	buf := make([]*models.Form, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f formDo) FindInBatches(result *[]*models.Form, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f formDo) Attrs(attrs ...field.AssignExpr) IFormDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f formDo) Assign(attrs ...field.AssignExpr) IFormDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f formDo) Joins(fields ...field.RelationField) IFormDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f formDo) Preload(fields ...field.RelationField) IFormDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f formDo) FirstOrInit() (*models.Form, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Form), nil
	}
}

func (f formDo) FirstOrCreate() (*models.Form, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Form), nil
	}
}

func (f formDo) FindByPage(offset int, limit int) (result []*models.Form, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f formDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f formDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f formDo) Delete(models ...*models.Form) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *formDo) withDO(do gen.Dao) *formDo {
	f.DO = *do.(*gen.DO)
	return f
}
