// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	ActivePassword *activePassword
	Coupon         *coupon
	Edge           *edge
	Feature        *feature
	Form           *form
	Plan           *plan
	Project        *project
	Question       *question
	QuestionOption *questionOption
	Response       *response
	Team           *team
	TeamUsage      *teamUsage
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	ActivePassword = &Q.ActivePassword
	Coupon = &Q.Coupon
	Edge = &Q.Edge
	Feature = &Q.Feature
	Form = &Q.Form
	Plan = &Q.Plan
	Project = &Q.Project
	Question = &Q.Question
	QuestionOption = &Q.QuestionOption
	Response = &Q.Response
	Team = &Q.Team
	TeamUsage = &Q.TeamUsage
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		ActivePassword: newActivePassword(db, opts...),
		Coupon:         newCoupon(db, opts...),
		Edge:           newEdge(db, opts...),
		Feature:        newFeature(db, opts...),
		Form:           newForm(db, opts...),
		Plan:           newPlan(db, opts...),
		Project:        newProject(db, opts...),
		Question:       newQuestion(db, opts...),
		QuestionOption: newQuestionOption(db, opts...),
		Response:       newResponse(db, opts...),
		Team:           newTeam(db, opts...),
		TeamUsage:      newTeamUsage(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	ActivePassword activePassword
	Coupon         coupon
	Edge           edge
	Feature        feature
	Form           form
	Plan           plan
	Project        project
	Question       question
	QuestionOption questionOption
	Response       response
	Team           team
	TeamUsage      teamUsage
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ActivePassword: q.ActivePassword.clone(db),
		Coupon:         q.Coupon.clone(db),
		Edge:           q.Edge.clone(db),
		Feature:        q.Feature.clone(db),
		Form:           q.Form.clone(db),
		Plan:           q.Plan.clone(db),
		Project:        q.Project.clone(db),
		Question:       q.Question.clone(db),
		QuestionOption: q.QuestionOption.clone(db),
		Response:       q.Response.clone(db),
		Team:           q.Team.clone(db),
		TeamUsage:      q.TeamUsage.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		ActivePassword: q.ActivePassword.replaceDB(db),
		Coupon:         q.Coupon.replaceDB(db),
		Edge:           q.Edge.replaceDB(db),
		Feature:        q.Feature.replaceDB(db),
		Form:           q.Form.replaceDB(db),
		Plan:           q.Plan.replaceDB(db),
		Project:        q.Project.replaceDB(db),
		Question:       q.Question.replaceDB(db),
		QuestionOption: q.QuestionOption.replaceDB(db),
		Response:       q.Response.replaceDB(db),
		Team:           q.Team.replaceDB(db),
		TeamUsage:      q.TeamUsage.replaceDB(db),
	}
}

type queryCtx struct {
	ActivePassword IActivePasswordDo
	Coupon         ICouponDo
	Edge           IEdgeDo
	Feature        IFeatureDo
	Form           IFormDo
	Plan           IPlanDo
	Project        IProjectDo
	Question       IQuestionDo
	QuestionOption IQuestionOptionDo
	Response       IResponseDo
	Team           ITeamDo
	TeamUsage      ITeamUsageDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		ActivePassword: q.ActivePassword.WithContext(ctx),
		Coupon:         q.Coupon.WithContext(ctx),
		Edge:           q.Edge.WithContext(ctx),
		Feature:        q.Feature.WithContext(ctx),
		Form:           q.Form.WithContext(ctx),
		Plan:           q.Plan.WithContext(ctx),
		Project:        q.Project.WithContext(ctx),
		Question:       q.Question.WithContext(ctx),
		QuestionOption: q.QuestionOption.WithContext(ctx),
		Response:       q.Response.WithContext(ctx),
		Team:           q.Team.WithContext(ctx),
		TeamUsage:      q.TeamUsage.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
