// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newPlan(db *gorm.DB, opts ...gen.DOOption) plan {
	_plan := plan{}

	_plan.planDo.UseDB(db, opts...)
	_plan.planDo.UseModel(&models.Plan{})

	tableName := _plan.planDo.TableName()
	_plan.ALL = field.NewAsterisk(tableName)
	_plan.ID = field.NewString(tableName, "id")
	_plan.Name = field.NewString(tableName, "name")
	_plan.Description = field.NewString(tableName, "description")
	_plan.Price = field.NewFloat64(tableName, "price")
	_plan.Currency = field.NewString(tableName, "currency")
	_plan.Valid = field.NewBool(tableName, "valid")
	_plan.CreatedAt = field.NewTime(tableName, "createdAt")
	_plan.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_plan.Coupons = planHasManyCoupons{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Coupons", "models.Coupon"),
		Plan: struct {
			field.RelationField
			Coupons struct {
				field.RelationField
			}
			Features struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}
			Teams struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
				TeamUsage struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
					Project struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
						Forms struct {
							field.RelationField
						}
					}
					Team struct {
						field.RelationField
					}
					ActivePasswords struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
					Edges struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						SourceNode struct {
							field.RelationField
							Form struct {
								field.RelationField
							}
							Options struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}
							OutgoingEdges struct {
								field.RelationField
							}
							IncomingEdges struct {
								field.RelationField
							}
						}
						TargetNode struct {
							field.RelationField
						}
					}
					Questions struct {
						field.RelationField
					}
					Responses struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
				}
				Projects struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Coupons.Plan", "models.Plan"),
			Coupons: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Coupons.Plan.Coupons", "models.Coupon"),
			},
			Features: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Coupons.Plan.Features", "models.Feature"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Coupons.Plan.Features.Plan", "models.Plan"),
				},
			},
			Teams: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
				TeamUsage struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
					Project struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
						Forms struct {
							field.RelationField
						}
					}
					Team struct {
						field.RelationField
					}
					ActivePasswords struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
					Edges struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						SourceNode struct {
							field.RelationField
							Form struct {
								field.RelationField
							}
							Options struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}
							OutgoingEdges struct {
								field.RelationField
							}
							IncomingEdges struct {
								field.RelationField
							}
						}
						TargetNode struct {
							field.RelationField
						}
					}
					Questions struct {
						field.RelationField
					}
					Responses struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
				}
				Projects struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Coupons.Plan.Teams", "models.Team"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Coupons.Plan.Teams.Plan", "models.Plan"),
				},
				TeamUsage: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Coupons.Plan.Teams.TeamUsage", "models.TeamUsage"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.TeamUsage.Team", "models.Team"),
					},
				},
				Forms: struct {
					field.RelationField
					Project struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
						Forms struct {
							field.RelationField
						}
					}
					Team struct {
						field.RelationField
					}
					ActivePasswords struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
					Edges struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						SourceNode struct {
							field.RelationField
							Form struct {
								field.RelationField
							}
							Options struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}
							OutgoingEdges struct {
								field.RelationField
							}
							IncomingEdges struct {
								field.RelationField
							}
						}
						TargetNode struct {
							field.RelationField
						}
					}
					Questions struct {
						field.RelationField
					}
					Responses struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}
				}{
					RelationField: field.NewRelation("Coupons.Plan.Teams.Forms", "models.Form"),
					Project: struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
						Forms struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Project", "models.Project"),
						Team: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Project.Team", "models.Team"),
						},
						Forms: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Project.Forms", "models.Form"),
						},
					},
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Team", "models.Team"),
					},
					ActivePasswords: struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.ActivePasswords", "models.ActivePassword"),
						Form: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.ActivePasswords.Form", "models.Form"),
						},
					},
					Edges: struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						SourceNode struct {
							field.RelationField
							Form struct {
								field.RelationField
							}
							Options struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}
							OutgoingEdges struct {
								field.RelationField
							}
							IncomingEdges struct {
								field.RelationField
							}
						}
						TargetNode struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges", "models.Edge"),
						Form: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.Form", "models.Form"),
						},
						SourceNode: struct {
							field.RelationField
							Form struct {
								field.RelationField
							}
							Options struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}
							OutgoingEdges struct {
								field.RelationField
							}
							IncomingEdges struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode", "models.Question"),
							Form: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode.Form", "models.Form"),
							},
							Options: struct {
								field.RelationField
								Question struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode.Options", "models.QuestionOption"),
								Question: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode.Options.Question", "models.Question"),
								},
							},
							OutgoingEdges: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
							},
							IncomingEdges: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
							},
						},
						TargetNode: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Edges.TargetNode", "models.Question"),
						},
					},
					Questions: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Questions", "models.Question"),
					},
					Responses: struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Responses", "models.Response"),
						Form: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Coupons.Plan.Teams.Forms.Responses.Form", "models.Form"),
						},
					},
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Coupons.Plan.Teams.Projects", "models.Project"),
				},
			},
		},
	}

	_plan.Features = planHasManyFeatures{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Features", "models.Feature"),
	}

	_plan.Teams = planHasManyTeams{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Teams", "models.Team"),
	}

	_plan.fillFieldMap()

	return _plan
}

type plan struct {
	planDo

	ALL         field.Asterisk
	ID          field.String
	Name        field.String
	Description field.String
	Price       field.Float64
	Currency    field.String
	Valid       field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Coupons     planHasManyCoupons

	Features planHasManyFeatures

	Teams planHasManyTeams

	fieldMap map[string]field.Expr
}

func (p plan) Table(newTableName string) *plan {
	p.planDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plan) As(alias string) *plan {
	p.planDo.DO = *(p.planDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plan) updateTableName(table string) *plan {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.Price = field.NewFloat64(table, "price")
	p.Currency = field.NewString(table, "currency")
	p.Valid = field.NewBool(table, "valid")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *plan) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plan) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 11)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["price"] = p.Price
	p.fieldMap["currency"] = p.Currency
	p.fieldMap["valid"] = p.Valid
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt

}

func (p plan) clone(db *gorm.DB) plan {
	p.planDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Coupons.db = db.Session(&gorm.Session{Initialized: true})
	p.Coupons.db.Statement.ConnPool = db.Statement.ConnPool
	p.Features.db = db.Session(&gorm.Session{Initialized: true})
	p.Features.db.Statement.ConnPool = db.Statement.ConnPool
	p.Teams.db = db.Session(&gorm.Session{Initialized: true})
	p.Teams.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p plan) replaceDB(db *gorm.DB) plan {
	p.planDo.ReplaceDB(db)
	p.Coupons.db = db.Session(&gorm.Session{})
	p.Features.db = db.Session(&gorm.Session{})
	p.Teams.db = db.Session(&gorm.Session{})
	return p
}

type planHasManyCoupons struct {
	db *gorm.DB

	field.RelationField

	Plan struct {
		field.RelationField
		Coupons struct {
			field.RelationField
		}
		Features struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}
		Teams struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
			TeamUsage struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
						Form struct {
							field.RelationField
						}
						Options struct {
							field.RelationField
							Question struct {
								field.RelationField
							}
						}
						OutgoingEdges struct {
							field.RelationField
						}
						IncomingEdges struct {
							field.RelationField
						}
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}
			Projects struct {
				field.RelationField
			}
		}
	}
}

func (a planHasManyCoupons) Where(conds ...field.Expr) *planHasManyCoupons {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a planHasManyCoupons) WithContext(ctx context.Context) *planHasManyCoupons {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a planHasManyCoupons) Session(session *gorm.Session) *planHasManyCoupons {
	a.db = a.db.Session(session)
	return &a
}

func (a planHasManyCoupons) Model(m *models.Plan) *planHasManyCouponsTx {
	return &planHasManyCouponsTx{a.db.Model(m).Association(a.Name())}
}

func (a planHasManyCoupons) Unscoped() *planHasManyCoupons {
	a.db = a.db.Unscoped()
	return &a
}

type planHasManyCouponsTx struct{ tx *gorm.Association }

func (a planHasManyCouponsTx) Find() (result []*models.Coupon, err error) {
	return result, a.tx.Find(&result)
}

func (a planHasManyCouponsTx) Append(values ...*models.Coupon) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a planHasManyCouponsTx) Replace(values ...*models.Coupon) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a planHasManyCouponsTx) Delete(values ...*models.Coupon) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a planHasManyCouponsTx) Clear() error {
	return a.tx.Clear()
}

func (a planHasManyCouponsTx) Count() int64 {
	return a.tx.Count()
}

func (a planHasManyCouponsTx) Unscoped() *planHasManyCouponsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type planHasManyFeatures struct {
	db *gorm.DB

	field.RelationField
}

func (a planHasManyFeatures) Where(conds ...field.Expr) *planHasManyFeatures {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a planHasManyFeatures) WithContext(ctx context.Context) *planHasManyFeatures {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a planHasManyFeatures) Session(session *gorm.Session) *planHasManyFeatures {
	a.db = a.db.Session(session)
	return &a
}

func (a planHasManyFeatures) Model(m *models.Plan) *planHasManyFeaturesTx {
	return &planHasManyFeaturesTx{a.db.Model(m).Association(a.Name())}
}

func (a planHasManyFeatures) Unscoped() *planHasManyFeatures {
	a.db = a.db.Unscoped()
	return &a
}

type planHasManyFeaturesTx struct{ tx *gorm.Association }

func (a planHasManyFeaturesTx) Find() (result []*models.Feature, err error) {
	return result, a.tx.Find(&result)
}

func (a planHasManyFeaturesTx) Append(values ...*models.Feature) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a planHasManyFeaturesTx) Replace(values ...*models.Feature) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a planHasManyFeaturesTx) Delete(values ...*models.Feature) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a planHasManyFeaturesTx) Clear() error {
	return a.tx.Clear()
}

func (a planHasManyFeaturesTx) Count() int64 {
	return a.tx.Count()
}

func (a planHasManyFeaturesTx) Unscoped() *planHasManyFeaturesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type planHasManyTeams struct {
	db *gorm.DB

	field.RelationField
}

func (a planHasManyTeams) Where(conds ...field.Expr) *planHasManyTeams {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a planHasManyTeams) WithContext(ctx context.Context) *planHasManyTeams {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a planHasManyTeams) Session(session *gorm.Session) *planHasManyTeams {
	a.db = a.db.Session(session)
	return &a
}

func (a planHasManyTeams) Model(m *models.Plan) *planHasManyTeamsTx {
	return &planHasManyTeamsTx{a.db.Model(m).Association(a.Name())}
}

func (a planHasManyTeams) Unscoped() *planHasManyTeams {
	a.db = a.db.Unscoped()
	return &a
}

type planHasManyTeamsTx struct{ tx *gorm.Association }

func (a planHasManyTeamsTx) Find() (result []*models.Team, err error) {
	return result, a.tx.Find(&result)
}

func (a planHasManyTeamsTx) Append(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a planHasManyTeamsTx) Replace(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a planHasManyTeamsTx) Delete(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a planHasManyTeamsTx) Clear() error {
	return a.tx.Clear()
}

func (a planHasManyTeamsTx) Count() int64 {
	return a.tx.Count()
}

func (a planHasManyTeamsTx) Unscoped() *planHasManyTeamsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type planDo struct{ gen.DO }

type IPlanDo interface {
	gen.SubQuery
	Debug() IPlanDo
	WithContext(ctx context.Context) IPlanDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlanDo
	WriteDB() IPlanDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlanDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlanDo
	Not(conds ...gen.Condition) IPlanDo
	Or(conds ...gen.Condition) IPlanDo
	Select(conds ...field.Expr) IPlanDo
	Where(conds ...gen.Condition) IPlanDo
	Order(conds ...field.Expr) IPlanDo
	Distinct(cols ...field.Expr) IPlanDo
	Omit(cols ...field.Expr) IPlanDo
	Join(table schema.Tabler, on ...field.Expr) IPlanDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlanDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlanDo
	Group(cols ...field.Expr) IPlanDo
	Having(conds ...gen.Condition) IPlanDo
	Limit(limit int) IPlanDo
	Offset(offset int) IPlanDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlanDo
	Unscoped() IPlanDo
	Create(values ...*models.Plan) error
	CreateInBatches(values []*models.Plan, batchSize int) error
	Save(values ...*models.Plan) error
	First() (*models.Plan, error)
	Take() (*models.Plan, error)
	Last() (*models.Plan, error)
	Find() ([]*models.Plan, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Plan, err error)
	FindInBatches(result *[]*models.Plan, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Plan) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlanDo
	Assign(attrs ...field.AssignExpr) IPlanDo
	Joins(fields ...field.RelationField) IPlanDo
	Preload(fields ...field.RelationField) IPlanDo
	FirstOrInit() (*models.Plan, error)
	FirstOrCreate() (*models.Plan, error)
	FindByPage(offset int, limit int) (result []*models.Plan, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlanDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p planDo) Debug() IPlanDo {
	return p.withDO(p.DO.Debug())
}

func (p planDo) WithContext(ctx context.Context) IPlanDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p planDo) ReadDB() IPlanDo {
	return p.Clauses(dbresolver.Read)
}

func (p planDo) WriteDB() IPlanDo {
	return p.Clauses(dbresolver.Write)
}

func (p planDo) Session(config *gorm.Session) IPlanDo {
	return p.withDO(p.DO.Session(config))
}

func (p planDo) Clauses(conds ...clause.Expression) IPlanDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p planDo) Returning(value interface{}, columns ...string) IPlanDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p planDo) Not(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p planDo) Or(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p planDo) Select(conds ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p planDo) Where(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p planDo) Order(conds ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p planDo) Distinct(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p planDo) Omit(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p planDo) Join(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p planDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p planDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlanDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p planDo) Group(cols ...field.Expr) IPlanDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p planDo) Having(conds ...gen.Condition) IPlanDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p planDo) Limit(limit int) IPlanDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p planDo) Offset(offset int) IPlanDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p planDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlanDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p planDo) Unscoped() IPlanDo {
	return p.withDO(p.DO.Unscoped())
}

func (p planDo) Create(values ...*models.Plan) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p planDo) CreateInBatches(values []*models.Plan, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p planDo) Save(values ...*models.Plan) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p planDo) First() (*models.Plan, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Plan), nil
	}
}

func (p planDo) Take() (*models.Plan, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Plan), nil
	}
}

func (p planDo) Last() (*models.Plan, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Plan), nil
	}
}

func (p planDo) Find() ([]*models.Plan, error) {
	result, err := p.DO.Find()
	return result.([]*models.Plan), err
}

func (p planDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Plan, err error) {
	buf := make([]*models.Plan, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p planDo) FindInBatches(result *[]*models.Plan, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p planDo) Attrs(attrs ...field.AssignExpr) IPlanDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p planDo) Assign(attrs ...field.AssignExpr) IPlanDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p planDo) Joins(fields ...field.RelationField) IPlanDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p planDo) Preload(fields ...field.RelationField) IPlanDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p planDo) FirstOrInit() (*models.Plan, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Plan), nil
	}
}

func (p planDo) FirstOrCreate() (*models.Plan, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Plan), nil
	}
}

func (p planDo) FindByPage(offset int, limit int) (result []*models.Plan, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p planDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p planDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p planDo) Delete(models ...*models.Plan) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *planDo) withDO(do gen.Dao) *planDo {
	p.DO = *do.(*gen.DO)
	return p
}
