// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newProject(db *gorm.DB, opts ...gen.DOOption) project {
	_project := project{}

	_project.projectDo.UseDB(db, opts...)
	_project.projectDo.UseModel(&models.Project{})

	tableName := _project.projectDo.TableName()
	_project.ALL = field.NewAsterisk(tableName)
	_project.ID = field.NewString(tableName, "id")
	_project.Name = field.NewString(tableName, "name")
	_project.Description = field.NewString(tableName, "description")
	_project.TeamID = field.NewString(tableName, "teamId")
	_project.Valid = field.NewBool(tableName, "valid")
	_project.CreatedAt = field.NewTime(tableName, "createdAt")
	_project.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_project.Forms = projectHasManyForms{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Forms", "models.Form"),
		Project: struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}
			Forms struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Forms.Project", "models.Project"),
			Team: struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
				Transactions struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Forms.Project.Team", "models.Team"),
				Plan: struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Forms.Project.Team.Plan", "models.Plan"),
					Coupons: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Forms.Project.Team.Plan.Coupons", "models.Coupon"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Forms.Project.Team.Plan.Coupons.Plan", "models.Plan"),
						},
					},
					Features: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Forms.Project.Team.Plan.Features", "models.Feature"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Forms.Project.Team.Plan.Features.Plan", "models.Plan"),
						},
					},
					Teams: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Forms.Project.Team.Plan.Teams", "models.Team"),
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Forms.Project.Team.Forms", "models.Form"),
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Forms.Project.Team.Projects", "models.Project"),
				},
				Transactions: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Forms.Project.Team.Transactions", "models.Transaction"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Forms.Project.Team.Transactions.Team", "models.Team"),
					},
				},
			},
			Forms: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Forms.Project.Forms", "models.Form"),
			},
		},
		Team: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Forms.Team", "models.Team"),
		},
		ActivePasswords: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Forms.ActivePasswords", "models.ActivePassword"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Forms.ActivePasswords.Form", "models.Form"),
			},
		},
		Edges: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Forms.Edges", "models.Edge"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Forms.Edges.Form", "models.Form"),
			},
			SourceNode: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Forms.Edges.SourceNode", "models.Question"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Forms.Edges.SourceNode.Form", "models.Form"),
				},
				Options: struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Forms.Edges.SourceNode.Options", "models.QuestionOption"),
					Question: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Forms.Edges.SourceNode.Options.Question", "models.Question"),
					},
				},
				OutgoingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
				},
				IncomingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
				},
			},
			TargetNode: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Forms.Edges.TargetNode", "models.Question"),
			},
		},
		Questions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Forms.Questions", "models.Question"),
		},
		Responses: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Forms.Responses", "models.Response"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Forms.Responses.Form", "models.Form"),
			},
		},
	}

	_project.Team = projectBelongsToTeam{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Team", "models.Team"),
	}

	_project.fillFieldMap()

	return _project
}

type project struct {
	projectDo

	ALL         field.Asterisk
	ID          field.String
	Name        field.String
	Description field.String
	TeamID      field.String
	Valid       field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time
	Forms       projectHasManyForms

	Team projectBelongsToTeam

	fieldMap map[string]field.Expr
}

func (p project) Table(newTableName string) *project {
	p.projectDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p project) As(alias string) *project {
	p.projectDo.DO = *(p.projectDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *project) updateTableName(table string) *project {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewString(table, "id")
	p.Name = field.NewString(table, "name")
	p.Description = field.NewString(table, "description")
	p.TeamID = field.NewString(table, "teamId")
	p.Valid = field.NewBool(table, "valid")
	p.CreatedAt = field.NewTime(table, "createdAt")
	p.UpdatedAt = field.NewTime(table, "updatedAt")

	p.fillFieldMap()

	return p
}

func (p *project) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *project) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 9)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["description"] = p.Description
	p.fieldMap["teamId"] = p.TeamID
	p.fieldMap["valid"] = p.Valid
	p.fieldMap["createdAt"] = p.CreatedAt
	p.fieldMap["updatedAt"] = p.UpdatedAt

}

func (p project) clone(db *gorm.DB) project {
	p.projectDo.ReplaceConnPool(db.Statement.ConnPool)
	p.Forms.db = db.Session(&gorm.Session{Initialized: true})
	p.Forms.db.Statement.ConnPool = db.Statement.ConnPool
	p.Team.db = db.Session(&gorm.Session{Initialized: true})
	p.Team.db.Statement.ConnPool = db.Statement.ConnPool
	return p
}

func (p project) replaceDB(db *gorm.DB) project {
	p.projectDo.ReplaceDB(db)
	p.Forms.db = db.Session(&gorm.Session{})
	p.Team.db = db.Session(&gorm.Session{})
	return p
}

type projectHasManyForms struct {
	db *gorm.DB

	field.RelationField

	Project struct {
		field.RelationField
		Team struct {
			field.RelationField
			Plan struct {
				field.RelationField
				Coupons struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Features struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Teams struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
			Projects struct {
				field.RelationField
			}
			Transactions struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
		}
		Forms struct {
			field.RelationField
		}
	}
	Team struct {
		field.RelationField
	}
	ActivePasswords struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
	Edges struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
		SourceNode struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			Options struct {
				field.RelationField
				Question struct {
					field.RelationField
				}
			}
			OutgoingEdges struct {
				field.RelationField
			}
			IncomingEdges struct {
				field.RelationField
			}
		}
		TargetNode struct {
			field.RelationField
		}
	}
	Questions struct {
		field.RelationField
	}
	Responses struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
}

func (a projectHasManyForms) Where(conds ...field.Expr) *projectHasManyForms {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a projectHasManyForms) WithContext(ctx context.Context) *projectHasManyForms {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a projectHasManyForms) Session(session *gorm.Session) *projectHasManyForms {
	a.db = a.db.Session(session)
	return &a
}

func (a projectHasManyForms) Model(m *models.Project) *projectHasManyFormsTx {
	return &projectHasManyFormsTx{a.db.Model(m).Association(a.Name())}
}

func (a projectHasManyForms) Unscoped() *projectHasManyForms {
	a.db = a.db.Unscoped()
	return &a
}

type projectHasManyFormsTx struct{ tx *gorm.Association }

func (a projectHasManyFormsTx) Find() (result []*models.Form, err error) {
	return result, a.tx.Find(&result)
}

func (a projectHasManyFormsTx) Append(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a projectHasManyFormsTx) Replace(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a projectHasManyFormsTx) Delete(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a projectHasManyFormsTx) Clear() error {
	return a.tx.Clear()
}

func (a projectHasManyFormsTx) Count() int64 {
	return a.tx.Count()
}

func (a projectHasManyFormsTx) Unscoped() *projectHasManyFormsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type projectBelongsToTeam struct {
	db *gorm.DB

	field.RelationField
}

func (a projectBelongsToTeam) Where(conds ...field.Expr) *projectBelongsToTeam {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a projectBelongsToTeam) WithContext(ctx context.Context) *projectBelongsToTeam {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a projectBelongsToTeam) Session(session *gorm.Session) *projectBelongsToTeam {
	a.db = a.db.Session(session)
	return &a
}

func (a projectBelongsToTeam) Model(m *models.Project) *projectBelongsToTeamTx {
	return &projectBelongsToTeamTx{a.db.Model(m).Association(a.Name())}
}

func (a projectBelongsToTeam) Unscoped() *projectBelongsToTeam {
	a.db = a.db.Unscoped()
	return &a
}

type projectBelongsToTeamTx struct{ tx *gorm.Association }

func (a projectBelongsToTeamTx) Find() (result *models.Team, err error) {
	return result, a.tx.Find(&result)
}

func (a projectBelongsToTeamTx) Append(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a projectBelongsToTeamTx) Replace(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a projectBelongsToTeamTx) Delete(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a projectBelongsToTeamTx) Clear() error {
	return a.tx.Clear()
}

func (a projectBelongsToTeamTx) Count() int64 {
	return a.tx.Count()
}

func (a projectBelongsToTeamTx) Unscoped() *projectBelongsToTeamTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type projectDo struct{ gen.DO }

type IProjectDo interface {
	gen.SubQuery
	Debug() IProjectDo
	WithContext(ctx context.Context) IProjectDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IProjectDo
	WriteDB() IProjectDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IProjectDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IProjectDo
	Not(conds ...gen.Condition) IProjectDo
	Or(conds ...gen.Condition) IProjectDo
	Select(conds ...field.Expr) IProjectDo
	Where(conds ...gen.Condition) IProjectDo
	Order(conds ...field.Expr) IProjectDo
	Distinct(cols ...field.Expr) IProjectDo
	Omit(cols ...field.Expr) IProjectDo
	Join(table schema.Tabler, on ...field.Expr) IProjectDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IProjectDo
	RightJoin(table schema.Tabler, on ...field.Expr) IProjectDo
	Group(cols ...field.Expr) IProjectDo
	Having(conds ...gen.Condition) IProjectDo
	Limit(limit int) IProjectDo
	Offset(offset int) IProjectDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectDo
	Unscoped() IProjectDo
	Create(values ...*models.Project) error
	CreateInBatches(values []*models.Project, batchSize int) error
	Save(values ...*models.Project) error
	First() (*models.Project, error)
	Take() (*models.Project, error)
	Last() (*models.Project, error)
	Find() ([]*models.Project, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Project, err error)
	FindInBatches(result *[]*models.Project, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Project) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IProjectDo
	Assign(attrs ...field.AssignExpr) IProjectDo
	Joins(fields ...field.RelationField) IProjectDo
	Preload(fields ...field.RelationField) IProjectDo
	FirstOrInit() (*models.Project, error)
	FirstOrCreate() (*models.Project, error)
	FindByPage(offset int, limit int) (result []*models.Project, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IProjectDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p projectDo) Debug() IProjectDo {
	return p.withDO(p.DO.Debug())
}

func (p projectDo) WithContext(ctx context.Context) IProjectDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p projectDo) ReadDB() IProjectDo {
	return p.Clauses(dbresolver.Read)
}

func (p projectDo) WriteDB() IProjectDo {
	return p.Clauses(dbresolver.Write)
}

func (p projectDo) Session(config *gorm.Session) IProjectDo {
	return p.withDO(p.DO.Session(config))
}

func (p projectDo) Clauses(conds ...clause.Expression) IProjectDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p projectDo) Returning(value interface{}, columns ...string) IProjectDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p projectDo) Not(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p projectDo) Or(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p projectDo) Select(conds ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p projectDo) Where(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p projectDo) Order(conds ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p projectDo) Distinct(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p projectDo) Omit(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p projectDo) Join(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p projectDo) LeftJoin(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p projectDo) RightJoin(table schema.Tabler, on ...field.Expr) IProjectDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p projectDo) Group(cols ...field.Expr) IProjectDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p projectDo) Having(conds ...gen.Condition) IProjectDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p projectDo) Limit(limit int) IProjectDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p projectDo) Offset(offset int) IProjectDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p projectDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IProjectDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p projectDo) Unscoped() IProjectDo {
	return p.withDO(p.DO.Unscoped())
}

func (p projectDo) Create(values ...*models.Project) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p projectDo) CreateInBatches(values []*models.Project, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p projectDo) Save(values ...*models.Project) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p projectDo) First() (*models.Project, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Project), nil
	}
}

func (p projectDo) Take() (*models.Project, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Project), nil
	}
}

func (p projectDo) Last() (*models.Project, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Project), nil
	}
}

func (p projectDo) Find() ([]*models.Project, error) {
	result, err := p.DO.Find()
	return result.([]*models.Project), err
}

func (p projectDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Project, err error) {
	buf := make([]*models.Project, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p projectDo) FindInBatches(result *[]*models.Project, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p projectDo) Attrs(attrs ...field.AssignExpr) IProjectDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p projectDo) Assign(attrs ...field.AssignExpr) IProjectDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p projectDo) Joins(fields ...field.RelationField) IProjectDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p projectDo) Preload(fields ...field.RelationField) IProjectDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p projectDo) FirstOrInit() (*models.Project, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Project), nil
	}
}

func (p projectDo) FirstOrCreate() (*models.Project, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Project), nil
	}
}

func (p projectDo) FindByPage(offset int, limit int) (result []*models.Project, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p projectDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p projectDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p projectDo) Delete(models ...*models.Project) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *projectDo) withDO(do gen.Dao) *projectDo {
	p.DO = *do.(*gen.DO)
	return p
}
