// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newQuestionOption(db *gorm.DB, opts ...gen.DOOption) questionOption {
	_questionOption := questionOption{}

	_questionOption.questionOptionDo.UseDB(db, opts...)
	_questionOption.questionOptionDo.UseModel(&models.QuestionOption{})

	tableName := _questionOption.questionOptionDo.TableName()
	_questionOption.ALL = field.NewAsterisk(tableName)
	_questionOption.ID = field.NewString(tableName, "id")
	_questionOption.QuestionID = field.NewString(tableName, "questionId")
	_questionOption.Label = field.NewString(tableName, "label")
	_questionOption.Value = field.NewString(tableName, "value")
	_questionOption.SortOrder = field.NewInt(tableName, "sortOrder")
	_questionOption.Question = questionOptionBelongsToQuestion{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Question", "models.Question"),
		Form: struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					TeamUsage struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Question.Form", "models.Form"),
			Project: struct {
				field.RelationField
				Team struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					TeamUsage struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Question.Form.Project", "models.Project"),
				Team: struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					TeamUsage struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Question.Form.Project.Team", "models.Team"),
					Plan: struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Question.Form.Project.Team.Plan", "models.Plan"),
						Coupons: struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Question.Form.Project.Team.Plan.Coupons", "models.Coupon"),
							Plan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Question.Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
							},
						},
						Features: struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Question.Form.Project.Team.Plan.Features", "models.Feature"),
							Plan: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Question.Form.Project.Team.Plan.Features.Plan", "models.Plan"),
							},
						},
						Teams: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Question.Form.Project.Team.Plan.Teams", "models.Team"),
						},
					},
					TeamUsage: struct {
						field.RelationField
						Team struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Question.Form.Project.Team.TeamUsage", "models.TeamUsage"),
						Team: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Question.Form.Project.Team.TeamUsage.Team", "models.Team"),
						},
					},
					Forms: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Question.Form.Project.Team.Forms", "models.Form"),
					},
					Projects: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Question.Form.Project.Team.Projects", "models.Project"),
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.Project.Forms", "models.Form"),
				},
			},
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Question.Form.Team", "models.Team"),
			},
			ActivePasswords: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Question.Form.ActivePasswords", "models.ActivePassword"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.ActivePasswords.Form", "models.Form"),
				},
			},
			Edges: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
				}
				TargetNode struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Question.Form.Edges", "models.Edge"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.Edges.Form", "models.Form"),
				},
				SourceNode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.Edges.SourceNode", "models.Question"),
				},
				TargetNode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.Edges.TargetNode", "models.Question"),
				},
			},
			Questions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Question.Form.Questions", "models.Question"),
			},
			Responses: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Question.Form.Responses", "models.Response"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Question.Form.Responses.Form", "models.Form"),
				},
			},
		},
		Options: struct {
			field.RelationField
			Question struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Question.Options", "models.QuestionOption"),
			Question: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Question.Options.Question", "models.Question"),
			},
		},
		OutgoingEdges: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Question.OutgoingEdges", "models.Edge"),
		},
		IncomingEdges: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Question.IncomingEdges", "models.Edge"),
		},
	}

	_questionOption.fillFieldMap()

	return _questionOption
}

type questionOption struct {
	questionOptionDo

	ALL        field.Asterisk
	ID         field.String
	QuestionID field.String
	Label      field.String
	Value      field.String
	SortOrder  field.Int
	Question   questionOptionBelongsToQuestion

	fieldMap map[string]field.Expr
}

func (q questionOption) Table(newTableName string) *questionOption {
	q.questionOptionDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q questionOption) As(alias string) *questionOption {
	q.questionOptionDo.DO = *(q.questionOptionDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *questionOption) updateTableName(table string) *questionOption {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewString(table, "id")
	q.QuestionID = field.NewString(table, "questionId")
	q.Label = field.NewString(table, "label")
	q.Value = field.NewString(table, "value")
	q.SortOrder = field.NewInt(table, "sortOrder")

	q.fillFieldMap()

	return q
}

func (q *questionOption) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *questionOption) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 6)
	q.fieldMap["id"] = q.ID
	q.fieldMap["questionId"] = q.QuestionID
	q.fieldMap["label"] = q.Label
	q.fieldMap["value"] = q.Value
	q.fieldMap["sortOrder"] = q.SortOrder

}

func (q questionOption) clone(db *gorm.DB) questionOption {
	q.questionOptionDo.ReplaceConnPool(db.Statement.ConnPool)
	q.Question.db = db.Session(&gorm.Session{Initialized: true})
	q.Question.db.Statement.ConnPool = db.Statement.ConnPool
	return q
}

func (q questionOption) replaceDB(db *gorm.DB) questionOption {
	q.questionOptionDo.ReplaceDB(db)
	q.Question.db = db.Session(&gorm.Session{})
	return q
}

type questionOptionBelongsToQuestion struct {
	db *gorm.DB

	field.RelationField

	Form struct {
		field.RelationField
		Project struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				TeamUsage struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
		}
		Team struct {
			field.RelationField
		}
		ActivePasswords struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
		Edges struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
			}
			TargetNode struct {
				field.RelationField
			}
		}
		Questions struct {
			field.RelationField
		}
		Responses struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
	}
	Options struct {
		field.RelationField
		Question struct {
			field.RelationField
		}
	}
	OutgoingEdges struct {
		field.RelationField
	}
	IncomingEdges struct {
		field.RelationField
	}
}

func (a questionOptionBelongsToQuestion) Where(conds ...field.Expr) *questionOptionBelongsToQuestion {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a questionOptionBelongsToQuestion) WithContext(ctx context.Context) *questionOptionBelongsToQuestion {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a questionOptionBelongsToQuestion) Session(session *gorm.Session) *questionOptionBelongsToQuestion {
	a.db = a.db.Session(session)
	return &a
}

func (a questionOptionBelongsToQuestion) Model(m *models.QuestionOption) *questionOptionBelongsToQuestionTx {
	return &questionOptionBelongsToQuestionTx{a.db.Model(m).Association(a.Name())}
}

func (a questionOptionBelongsToQuestion) Unscoped() *questionOptionBelongsToQuestion {
	a.db = a.db.Unscoped()
	return &a
}

type questionOptionBelongsToQuestionTx struct{ tx *gorm.Association }

func (a questionOptionBelongsToQuestionTx) Find() (result *models.Question, err error) {
	return result, a.tx.Find(&result)
}

func (a questionOptionBelongsToQuestionTx) Append(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a questionOptionBelongsToQuestionTx) Replace(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a questionOptionBelongsToQuestionTx) Delete(values ...*models.Question) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a questionOptionBelongsToQuestionTx) Clear() error {
	return a.tx.Clear()
}

func (a questionOptionBelongsToQuestionTx) Count() int64 {
	return a.tx.Count()
}

func (a questionOptionBelongsToQuestionTx) Unscoped() *questionOptionBelongsToQuestionTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type questionOptionDo struct{ gen.DO }

type IQuestionOptionDo interface {
	gen.SubQuery
	Debug() IQuestionOptionDo
	WithContext(ctx context.Context) IQuestionOptionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuestionOptionDo
	WriteDB() IQuestionOptionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuestionOptionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuestionOptionDo
	Not(conds ...gen.Condition) IQuestionOptionDo
	Or(conds ...gen.Condition) IQuestionOptionDo
	Select(conds ...field.Expr) IQuestionOptionDo
	Where(conds ...gen.Condition) IQuestionOptionDo
	Order(conds ...field.Expr) IQuestionOptionDo
	Distinct(cols ...field.Expr) IQuestionOptionDo
	Omit(cols ...field.Expr) IQuestionOptionDo
	Join(table schema.Tabler, on ...field.Expr) IQuestionOptionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuestionOptionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuestionOptionDo
	Group(cols ...field.Expr) IQuestionOptionDo
	Having(conds ...gen.Condition) IQuestionOptionDo
	Limit(limit int) IQuestionOptionDo
	Offset(offset int) IQuestionOptionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuestionOptionDo
	Unscoped() IQuestionOptionDo
	Create(values ...*models.QuestionOption) error
	CreateInBatches(values []*models.QuestionOption, batchSize int) error
	Save(values ...*models.QuestionOption) error
	First() (*models.QuestionOption, error)
	Take() (*models.QuestionOption, error)
	Last() (*models.QuestionOption, error)
	Find() ([]*models.QuestionOption, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QuestionOption, err error)
	FindInBatches(result *[]*models.QuestionOption, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.QuestionOption) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuestionOptionDo
	Assign(attrs ...field.AssignExpr) IQuestionOptionDo
	Joins(fields ...field.RelationField) IQuestionOptionDo
	Preload(fields ...field.RelationField) IQuestionOptionDo
	FirstOrInit() (*models.QuestionOption, error)
	FirstOrCreate() (*models.QuestionOption, error)
	FindByPage(offset int, limit int) (result []*models.QuestionOption, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuestionOptionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q questionOptionDo) Debug() IQuestionOptionDo {
	return q.withDO(q.DO.Debug())
}

func (q questionOptionDo) WithContext(ctx context.Context) IQuestionOptionDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q questionOptionDo) ReadDB() IQuestionOptionDo {
	return q.Clauses(dbresolver.Read)
}

func (q questionOptionDo) WriteDB() IQuestionOptionDo {
	return q.Clauses(dbresolver.Write)
}

func (q questionOptionDo) Session(config *gorm.Session) IQuestionOptionDo {
	return q.withDO(q.DO.Session(config))
}

func (q questionOptionDo) Clauses(conds ...clause.Expression) IQuestionOptionDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q questionOptionDo) Returning(value interface{}, columns ...string) IQuestionOptionDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q questionOptionDo) Not(conds ...gen.Condition) IQuestionOptionDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q questionOptionDo) Or(conds ...gen.Condition) IQuestionOptionDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q questionOptionDo) Select(conds ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q questionOptionDo) Where(conds ...gen.Condition) IQuestionOptionDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q questionOptionDo) Order(conds ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q questionOptionDo) Distinct(cols ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q questionOptionDo) Omit(cols ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q questionOptionDo) Join(table schema.Tabler, on ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q questionOptionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q questionOptionDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q questionOptionDo) Group(cols ...field.Expr) IQuestionOptionDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q questionOptionDo) Having(conds ...gen.Condition) IQuestionOptionDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q questionOptionDo) Limit(limit int) IQuestionOptionDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q questionOptionDo) Offset(offset int) IQuestionOptionDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q questionOptionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuestionOptionDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q questionOptionDo) Unscoped() IQuestionOptionDo {
	return q.withDO(q.DO.Unscoped())
}

func (q questionOptionDo) Create(values ...*models.QuestionOption) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q questionOptionDo) CreateInBatches(values []*models.QuestionOption, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q questionOptionDo) Save(values ...*models.QuestionOption) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q questionOptionDo) First() (*models.QuestionOption, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.QuestionOption), nil
	}
}

func (q questionOptionDo) Take() (*models.QuestionOption, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.QuestionOption), nil
	}
}

func (q questionOptionDo) Last() (*models.QuestionOption, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.QuestionOption), nil
	}
}

func (q questionOptionDo) Find() ([]*models.QuestionOption, error) {
	result, err := q.DO.Find()
	return result.([]*models.QuestionOption), err
}

func (q questionOptionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.QuestionOption, err error) {
	buf := make([]*models.QuestionOption, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q questionOptionDo) FindInBatches(result *[]*models.QuestionOption, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q questionOptionDo) Attrs(attrs ...field.AssignExpr) IQuestionOptionDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q questionOptionDo) Assign(attrs ...field.AssignExpr) IQuestionOptionDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q questionOptionDo) Joins(fields ...field.RelationField) IQuestionOptionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q questionOptionDo) Preload(fields ...field.RelationField) IQuestionOptionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q questionOptionDo) FirstOrInit() (*models.QuestionOption, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.QuestionOption), nil
	}
}

func (q questionOptionDo) FirstOrCreate() (*models.QuestionOption, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.QuestionOption), nil
	}
}

func (q questionOptionDo) FindByPage(offset int, limit int) (result []*models.QuestionOption, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q questionOptionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q questionOptionDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q questionOptionDo) Delete(models ...*models.QuestionOption) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *questionOptionDo) withDO(do gen.Dao) *questionOptionDo {
	q.DO = *do.(*gen.DO)
	return q
}
