// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newQuestion(db *gorm.DB, opts ...gen.DOOption) question {
	_question := question{}

	_question.questionDo.UseDB(db, opts...)
	_question.questionDo.UseModel(&models.Question{})

	tableName := _question.questionDo.TableName()
	_question.ALL = field.NewAsterisk(tableName)
	_question.ID = field.NewString(tableName, "id")
	_question.FormID = field.NewString(tableName, "formId")
	_question.Title = field.NewString(tableName, "title")
	_question.Placeholder = field.NewString(tableName, "placeholder")
	_question.Description = field.NewString(tableName, "description")
	_question.Required = field.NewBool(tableName, "required")
	_question.Type = field.NewString(tableName, "type")
	_question.Metadata = field.NewField(tableName, "metadata")
	_question.PosX = field.NewInt(tableName, "posX")
	_question.PosY = field.NewInt(tableName, "posY")
	_question.SortOrder = field.NewInt(tableName, "sortOrder")
	_question.Options = questionHasManyOptions{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Options", "models.QuestionOption"),
		Question: struct {
			field.RelationField
			Form struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
						Plan struct {
							field.RelationField
							Coupons struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Features struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Teams struct {
								field.RelationField
							}
						}
						Forms struct {
							field.RelationField
						}
						Projects struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}
			Options struct {
				field.RelationField
			}
			OutgoingEdges struct {
				field.RelationField
			}
			IncomingEdges struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Options.Question", "models.Question"),
			Form: struct {
				field.RelationField
				Project struct {
					field.RelationField
					Team struct {
						field.RelationField
						Plan struct {
							field.RelationField
							Coupons struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Features struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Teams struct {
								field.RelationField
							}
						}
						Forms struct {
							field.RelationField
						}
						Projects struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
				}
				Team struct {
					field.RelationField
				}
				ActivePasswords struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
				Edges struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
					}
					TargetNode struct {
						field.RelationField
					}
				}
				Questions struct {
					field.RelationField
				}
				Responses struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}
			}{
				RelationField: field.NewRelation("Options.Question.Form", "models.Form"),
				Project: struct {
					field.RelationField
					Team struct {
						field.RelationField
						Plan struct {
							field.RelationField
							Coupons struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Features struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Teams struct {
								field.RelationField
							}
						}
						Forms struct {
							field.RelationField
						}
						Projects struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Options.Question.Form.Project", "models.Project"),
					Team: struct {
						field.RelationField
						Plan struct {
							field.RelationField
							Coupons struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Features struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Teams struct {
								field.RelationField
							}
						}
						Forms struct {
							field.RelationField
						}
						Projects struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Options.Question.Form.Project.Team", "models.Team"),
						Plan: struct {
							field.RelationField
							Coupons struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Features struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}
							Teams struct {
								field.RelationField
							}
						}{
							RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan", "models.Plan"),
							Coupons: struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan.Coupons", "models.Coupon"),
								Plan: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
								},
							},
							Features: struct {
								field.RelationField
								Plan struct {
									field.RelationField
								}
							}{
								RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan.Features", "models.Feature"),
								Plan: struct {
									field.RelationField
								}{
									RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan.Features.Plan", "models.Plan"),
								},
							},
							Teams: struct {
								field.RelationField
							}{
								RelationField: field.NewRelation("Options.Question.Form.Project.Team.Plan.Teams", "models.Team"),
							},
						},
						Forms: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Options.Question.Form.Project.Team.Forms", "models.Form"),
						},
						Projects: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Options.Question.Form.Project.Team.Projects", "models.Project"),
						},
					},
					Forms: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.Project.Forms", "models.Form"),
					},
				},
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Options.Question.Form.Team", "models.Team"),
				},
				ActivePasswords: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Options.Question.Form.ActivePasswords", "models.ActivePassword"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.ActivePasswords.Form", "models.Form"),
					},
				},
				Edges: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					SourceNode struct {
						field.RelationField
					}
					TargetNode struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Options.Question.Form.Edges", "models.Edge"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.Edges.Form", "models.Form"),
					},
					SourceNode: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.Edges.SourceNode", "models.Question"),
					},
					TargetNode: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.Edges.TargetNode", "models.Question"),
					},
				},
				Questions: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Options.Question.Form.Questions", "models.Question"),
				},
				Responses: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Options.Question.Form.Responses", "models.Response"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Options.Question.Form.Responses.Form", "models.Form"),
					},
				},
			},
			Options: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Options.Question.Options", "models.QuestionOption"),
			},
			OutgoingEdges: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Options.Question.OutgoingEdges", "models.Edge"),
			},
			IncomingEdges: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Options.Question.IncomingEdges", "models.Edge"),
			},
		},
	}

	_question.OutgoingEdges = questionHasManyOutgoingEdges{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("OutgoingEdges", "models.Edge"),
	}

	_question.IncomingEdges = questionHasManyIncomingEdges{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("IncomingEdges", "models.Edge"),
	}

	_question.Form = questionBelongsToForm{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Form", "models.Form"),
	}

	_question.fillFieldMap()

	return _question
}

type question struct {
	questionDo

	ALL         field.Asterisk
	ID          field.String
	FormID      field.String
	Title       field.String
	Placeholder field.String
	Description field.String
	Required    field.Bool
	Type        field.String
	Metadata    field.Field
	PosX        field.Int
	PosY        field.Int
	SortOrder   field.Int
	Options     questionHasManyOptions

	OutgoingEdges questionHasManyOutgoingEdges

	IncomingEdges questionHasManyIncomingEdges

	Form questionBelongsToForm

	fieldMap map[string]field.Expr
}

func (q question) Table(newTableName string) *question {
	q.questionDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q question) As(alias string) *question {
	q.questionDo.DO = *(q.questionDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *question) updateTableName(table string) *question {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewString(table, "id")
	q.FormID = field.NewString(table, "formId")
	q.Title = field.NewString(table, "title")
	q.Placeholder = field.NewString(table, "placeholder")
	q.Description = field.NewString(table, "description")
	q.Required = field.NewBool(table, "required")
	q.Type = field.NewString(table, "type")
	q.Metadata = field.NewField(table, "metadata")
	q.PosX = field.NewInt(table, "posX")
	q.PosY = field.NewInt(table, "posY")
	q.SortOrder = field.NewInt(table, "sortOrder")

	q.fillFieldMap()

	return q
}

func (q *question) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *question) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 15)
	q.fieldMap["id"] = q.ID
	q.fieldMap["formId"] = q.FormID
	q.fieldMap["title"] = q.Title
	q.fieldMap["placeholder"] = q.Placeholder
	q.fieldMap["description"] = q.Description
	q.fieldMap["required"] = q.Required
	q.fieldMap["type"] = q.Type
	q.fieldMap["metadata"] = q.Metadata
	q.fieldMap["posX"] = q.PosX
	q.fieldMap["posY"] = q.PosY
	q.fieldMap["sortOrder"] = q.SortOrder

}

func (q question) clone(db *gorm.DB) question {
	q.questionDo.ReplaceConnPool(db.Statement.ConnPool)
	q.Options.db = db.Session(&gorm.Session{Initialized: true})
	q.Options.db.Statement.ConnPool = db.Statement.ConnPool
	q.OutgoingEdges.db = db.Session(&gorm.Session{Initialized: true})
	q.OutgoingEdges.db.Statement.ConnPool = db.Statement.ConnPool
	q.IncomingEdges.db = db.Session(&gorm.Session{Initialized: true})
	q.IncomingEdges.db.Statement.ConnPool = db.Statement.ConnPool
	q.Form.db = db.Session(&gorm.Session{Initialized: true})
	q.Form.db.Statement.ConnPool = db.Statement.ConnPool
	return q
}

func (q question) replaceDB(db *gorm.DB) question {
	q.questionDo.ReplaceDB(db)
	q.Options.db = db.Session(&gorm.Session{})
	q.OutgoingEdges.db = db.Session(&gorm.Session{})
	q.IncomingEdges.db = db.Session(&gorm.Session{})
	q.Form.db = db.Session(&gorm.Session{})
	return q
}

type questionHasManyOptions struct {
	db *gorm.DB

	field.RelationField

	Question struct {
		field.RelationField
		Form struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
					Plan struct {
						field.RelationField
						Coupons struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Features struct {
							field.RelationField
							Plan struct {
								field.RelationField
							}
						}
						Teams struct {
							field.RelationField
						}
					}
					Forms struct {
						field.RelationField
					}
					Projects struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}
		Options struct {
			field.RelationField
		}
		OutgoingEdges struct {
			field.RelationField
		}
		IncomingEdges struct {
			field.RelationField
		}
	}
}

func (a questionHasManyOptions) Where(conds ...field.Expr) *questionHasManyOptions {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a questionHasManyOptions) WithContext(ctx context.Context) *questionHasManyOptions {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a questionHasManyOptions) Session(session *gorm.Session) *questionHasManyOptions {
	a.db = a.db.Session(session)
	return &a
}

func (a questionHasManyOptions) Model(m *models.Question) *questionHasManyOptionsTx {
	return &questionHasManyOptionsTx{a.db.Model(m).Association(a.Name())}
}

func (a questionHasManyOptions) Unscoped() *questionHasManyOptions {
	a.db = a.db.Unscoped()
	return &a
}

type questionHasManyOptionsTx struct{ tx *gorm.Association }

func (a questionHasManyOptionsTx) Find() (result []*models.QuestionOption, err error) {
	return result, a.tx.Find(&result)
}

func (a questionHasManyOptionsTx) Append(values ...*models.QuestionOption) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a questionHasManyOptionsTx) Replace(values ...*models.QuestionOption) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a questionHasManyOptionsTx) Delete(values ...*models.QuestionOption) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a questionHasManyOptionsTx) Clear() error {
	return a.tx.Clear()
}

func (a questionHasManyOptionsTx) Count() int64 {
	return a.tx.Count()
}

func (a questionHasManyOptionsTx) Unscoped() *questionHasManyOptionsTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type questionHasManyOutgoingEdges struct {
	db *gorm.DB

	field.RelationField
}

func (a questionHasManyOutgoingEdges) Where(conds ...field.Expr) *questionHasManyOutgoingEdges {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a questionHasManyOutgoingEdges) WithContext(ctx context.Context) *questionHasManyOutgoingEdges {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a questionHasManyOutgoingEdges) Session(session *gorm.Session) *questionHasManyOutgoingEdges {
	a.db = a.db.Session(session)
	return &a
}

func (a questionHasManyOutgoingEdges) Model(m *models.Question) *questionHasManyOutgoingEdgesTx {
	return &questionHasManyOutgoingEdgesTx{a.db.Model(m).Association(a.Name())}
}

func (a questionHasManyOutgoingEdges) Unscoped() *questionHasManyOutgoingEdges {
	a.db = a.db.Unscoped()
	return &a
}

type questionHasManyOutgoingEdgesTx struct{ tx *gorm.Association }

func (a questionHasManyOutgoingEdgesTx) Find() (result []*models.Edge, err error) {
	return result, a.tx.Find(&result)
}

func (a questionHasManyOutgoingEdgesTx) Append(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a questionHasManyOutgoingEdgesTx) Replace(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a questionHasManyOutgoingEdgesTx) Delete(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a questionHasManyOutgoingEdgesTx) Clear() error {
	return a.tx.Clear()
}

func (a questionHasManyOutgoingEdgesTx) Count() int64 {
	return a.tx.Count()
}

func (a questionHasManyOutgoingEdgesTx) Unscoped() *questionHasManyOutgoingEdgesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type questionHasManyIncomingEdges struct {
	db *gorm.DB

	field.RelationField
}

func (a questionHasManyIncomingEdges) Where(conds ...field.Expr) *questionHasManyIncomingEdges {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a questionHasManyIncomingEdges) WithContext(ctx context.Context) *questionHasManyIncomingEdges {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a questionHasManyIncomingEdges) Session(session *gorm.Session) *questionHasManyIncomingEdges {
	a.db = a.db.Session(session)
	return &a
}

func (a questionHasManyIncomingEdges) Model(m *models.Question) *questionHasManyIncomingEdgesTx {
	return &questionHasManyIncomingEdgesTx{a.db.Model(m).Association(a.Name())}
}

func (a questionHasManyIncomingEdges) Unscoped() *questionHasManyIncomingEdges {
	a.db = a.db.Unscoped()
	return &a
}

type questionHasManyIncomingEdgesTx struct{ tx *gorm.Association }

func (a questionHasManyIncomingEdgesTx) Find() (result []*models.Edge, err error) {
	return result, a.tx.Find(&result)
}

func (a questionHasManyIncomingEdgesTx) Append(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a questionHasManyIncomingEdgesTx) Replace(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a questionHasManyIncomingEdgesTx) Delete(values ...*models.Edge) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a questionHasManyIncomingEdgesTx) Clear() error {
	return a.tx.Clear()
}

func (a questionHasManyIncomingEdgesTx) Count() int64 {
	return a.tx.Count()
}

func (a questionHasManyIncomingEdgesTx) Unscoped() *questionHasManyIncomingEdgesTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type questionBelongsToForm struct {
	db *gorm.DB

	field.RelationField
}

func (a questionBelongsToForm) Where(conds ...field.Expr) *questionBelongsToForm {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a questionBelongsToForm) WithContext(ctx context.Context) *questionBelongsToForm {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a questionBelongsToForm) Session(session *gorm.Session) *questionBelongsToForm {
	a.db = a.db.Session(session)
	return &a
}

func (a questionBelongsToForm) Model(m *models.Question) *questionBelongsToFormTx {
	return &questionBelongsToFormTx{a.db.Model(m).Association(a.Name())}
}

func (a questionBelongsToForm) Unscoped() *questionBelongsToForm {
	a.db = a.db.Unscoped()
	return &a
}

type questionBelongsToFormTx struct{ tx *gorm.Association }

func (a questionBelongsToFormTx) Find() (result *models.Form, err error) {
	return result, a.tx.Find(&result)
}

func (a questionBelongsToFormTx) Append(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a questionBelongsToFormTx) Replace(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a questionBelongsToFormTx) Delete(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a questionBelongsToFormTx) Clear() error {
	return a.tx.Clear()
}

func (a questionBelongsToFormTx) Count() int64 {
	return a.tx.Count()
}

func (a questionBelongsToFormTx) Unscoped() *questionBelongsToFormTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type questionDo struct{ gen.DO }

type IQuestionDo interface {
	gen.SubQuery
	Debug() IQuestionDo
	WithContext(ctx context.Context) IQuestionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQuestionDo
	WriteDB() IQuestionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQuestionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQuestionDo
	Not(conds ...gen.Condition) IQuestionDo
	Or(conds ...gen.Condition) IQuestionDo
	Select(conds ...field.Expr) IQuestionDo
	Where(conds ...gen.Condition) IQuestionDo
	Order(conds ...field.Expr) IQuestionDo
	Distinct(cols ...field.Expr) IQuestionDo
	Omit(cols ...field.Expr) IQuestionDo
	Join(table schema.Tabler, on ...field.Expr) IQuestionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQuestionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQuestionDo
	Group(cols ...field.Expr) IQuestionDo
	Having(conds ...gen.Condition) IQuestionDo
	Limit(limit int) IQuestionDo
	Offset(offset int) IQuestionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQuestionDo
	Unscoped() IQuestionDo
	Create(values ...*models.Question) error
	CreateInBatches(values []*models.Question, batchSize int) error
	Save(values ...*models.Question) error
	First() (*models.Question, error)
	Take() (*models.Question, error)
	Last() (*models.Question, error)
	Find() ([]*models.Question, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Question, err error)
	FindInBatches(result *[]*models.Question, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Question) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQuestionDo
	Assign(attrs ...field.AssignExpr) IQuestionDo
	Joins(fields ...field.RelationField) IQuestionDo
	Preload(fields ...field.RelationField) IQuestionDo
	FirstOrInit() (*models.Question, error)
	FirstOrCreate() (*models.Question, error)
	FindByPage(offset int, limit int) (result []*models.Question, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQuestionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q questionDo) Debug() IQuestionDo {
	return q.withDO(q.DO.Debug())
}

func (q questionDo) WithContext(ctx context.Context) IQuestionDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q questionDo) ReadDB() IQuestionDo {
	return q.Clauses(dbresolver.Read)
}

func (q questionDo) WriteDB() IQuestionDo {
	return q.Clauses(dbresolver.Write)
}

func (q questionDo) Session(config *gorm.Session) IQuestionDo {
	return q.withDO(q.DO.Session(config))
}

func (q questionDo) Clauses(conds ...clause.Expression) IQuestionDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q questionDo) Returning(value interface{}, columns ...string) IQuestionDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q questionDo) Not(conds ...gen.Condition) IQuestionDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q questionDo) Or(conds ...gen.Condition) IQuestionDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q questionDo) Select(conds ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q questionDo) Where(conds ...gen.Condition) IQuestionDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q questionDo) Order(conds ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q questionDo) Distinct(cols ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q questionDo) Omit(cols ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q questionDo) Join(table schema.Tabler, on ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q questionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q questionDo) RightJoin(table schema.Tabler, on ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q questionDo) Group(cols ...field.Expr) IQuestionDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q questionDo) Having(conds ...gen.Condition) IQuestionDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q questionDo) Limit(limit int) IQuestionDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q questionDo) Offset(offset int) IQuestionDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q questionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQuestionDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q questionDo) Unscoped() IQuestionDo {
	return q.withDO(q.DO.Unscoped())
}

func (q questionDo) Create(values ...*models.Question) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q questionDo) CreateInBatches(values []*models.Question, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q questionDo) Save(values ...*models.Question) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q questionDo) First() (*models.Question, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Question), nil
	}
}

func (q questionDo) Take() (*models.Question, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Question), nil
	}
}

func (q questionDo) Last() (*models.Question, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Question), nil
	}
}

func (q questionDo) Find() ([]*models.Question, error) {
	result, err := q.DO.Find()
	return result.([]*models.Question), err
}

func (q questionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Question, err error) {
	buf := make([]*models.Question, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q questionDo) FindInBatches(result *[]*models.Question, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q questionDo) Attrs(attrs ...field.AssignExpr) IQuestionDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q questionDo) Assign(attrs ...field.AssignExpr) IQuestionDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q questionDo) Joins(fields ...field.RelationField) IQuestionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q questionDo) Preload(fields ...field.RelationField) IQuestionDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q questionDo) FirstOrInit() (*models.Question, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Question), nil
	}
}

func (q questionDo) FirstOrCreate() (*models.Question, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Question), nil
	}
}

func (q questionDo) FindByPage(offset int, limit int) (result []*models.Question, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q questionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q questionDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q questionDo) Delete(models ...*models.Question) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *questionDo) withDO(do gen.Dao) *questionDo {
	q.DO = *do.(*gen.DO)
	return q
}
