// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newResponse(db *gorm.DB, opts ...gen.DOOption) response {
	_response := response{}

	_response.responseDo.UseDB(db, opts...)
	_response.responseDo.UseModel(&models.Response{})

	tableName := _response.responseDo.TableName()
	_response.ALL = field.NewAsterisk(tableName)
	_response.ID = field.NewString(tableName, "id")
	_response.FormID = field.NewString(tableName, "formId")
	_response.UserID = field.NewString(tableName, "userId")
	_response.Data = field.NewField(tableName, "data")
	_response.MetaData = field.NewField(tableName, "metaData")
	_response.Tags = field.NewField(tableName, "tags")
	_response.Status = field.NewString(tableName, "status")
	_response.PartialSave = field.NewBool(tableName, "partialSave")
	_response.Notified = field.NewBool(tableName, "notified")
	_response.Valid = field.NewBool(tableName, "valid")
	_response.StartedAt = field.NewTime(tableName, "startedAt")
	_response.SubmittedAt = field.NewTime(tableName, "submittedAt")
	_response.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_response.Form = responseBelongsToForm{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Form", "models.Form"),
		Project: struct {
			field.RelationField
			Team struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				TeamUsage struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Project", "models.Project"),
			Team: struct {
				field.RelationField
				Plan struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}
				TeamUsage struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}
				Forms struct {
					field.RelationField
				}
				Projects struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Form.Project.Team", "models.Team"),
				Plan: struct {
					field.RelationField
					Coupons struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Features struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}
					Teams struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.Plan", "models.Plan"),
					Coupons: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons", "models.Coupon"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Coupons.Plan", "models.Plan"),
						},
					},
					Features: struct {
						field.RelationField
						Plan struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Features", "models.Feature"),
						Plan: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Form.Project.Team.Plan.Features.Plan", "models.Plan"),
						},
					},
					Teams: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.Plan.Teams", "models.Team"),
					},
				},
				TeamUsage: struct {
					field.RelationField
					Team struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Project.Team.TeamUsage", "models.TeamUsage"),
					Team: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Project.Team.TeamUsage.Team", "models.Team"),
					},
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Forms", "models.Form"),
				},
				Projects: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Project.Team.Projects", "models.Project"),
				},
			},
			Forms: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Project.Forms", "models.Form"),
			},
		},
		Team: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Team", "models.Team"),
		},
		ActivePasswords: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.ActivePasswords", "models.ActivePassword"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.ActivePasswords.Form", "models.Form"),
			},
		},
		Edges: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Edges", "models.Edge"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.Form", "models.Form"),
			},
			SourceNode: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Form.Edges.SourceNode", "models.Question"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Form", "models.Form"),
				},
				Options: struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.Options", "models.QuestionOption"),
					Question: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Form.Edges.SourceNode.Options.Question", "models.Question"),
					},
				},
				OutgoingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.OutgoingEdges", "models.Edge"),
				},
				IncomingEdges: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Form.Edges.SourceNode.IncomingEdges", "models.Edge"),
				},
			},
			TargetNode: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Edges.TargetNode", "models.Question"),
			},
		},
		Questions: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Form.Questions", "models.Question"),
		},
		Responses: struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Form.Responses", "models.Response"),
			Form: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Form.Responses.Form", "models.Form"),
			},
		},
	}

	_response.fillFieldMap()

	return _response
}

type response struct {
	responseDo

	ALL         field.Asterisk
	ID          field.String
	FormID      field.String
	UserID      field.String
	Data        field.Field
	MetaData    field.Field
	Tags        field.Field
	Status      field.String
	PartialSave field.Bool
	Notified    field.Bool
	Valid       field.Bool
	StartedAt   field.Time
	SubmittedAt field.Time
	UpdatedAt   field.Time
	Form        responseBelongsToForm

	fieldMap map[string]field.Expr
}

func (r response) Table(newTableName string) *response {
	r.responseDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r response) As(alias string) *response {
	r.responseDo.DO = *(r.responseDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *response) updateTableName(table string) *response {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.FormID = field.NewString(table, "formId")
	r.UserID = field.NewString(table, "userId")
	r.Data = field.NewField(table, "data")
	r.MetaData = field.NewField(table, "metaData")
	r.Tags = field.NewField(table, "tags")
	r.Status = field.NewString(table, "status")
	r.PartialSave = field.NewBool(table, "partialSave")
	r.Notified = field.NewBool(table, "notified")
	r.Valid = field.NewBool(table, "valid")
	r.StartedAt = field.NewTime(table, "startedAt")
	r.SubmittedAt = field.NewTime(table, "submittedAt")
	r.UpdatedAt = field.NewTime(table, "updatedAt")

	r.fillFieldMap()

	return r
}

func (r *response) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *response) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 14)
	r.fieldMap["id"] = r.ID
	r.fieldMap["formId"] = r.FormID
	r.fieldMap["userId"] = r.UserID
	r.fieldMap["data"] = r.Data
	r.fieldMap["metaData"] = r.MetaData
	r.fieldMap["tags"] = r.Tags
	r.fieldMap["status"] = r.Status
	r.fieldMap["partialSave"] = r.PartialSave
	r.fieldMap["notified"] = r.Notified
	r.fieldMap["valid"] = r.Valid
	r.fieldMap["startedAt"] = r.StartedAt
	r.fieldMap["submittedAt"] = r.SubmittedAt
	r.fieldMap["updatedAt"] = r.UpdatedAt

}

func (r response) clone(db *gorm.DB) response {
	r.responseDo.ReplaceConnPool(db.Statement.ConnPool)
	r.Form.db = db.Session(&gorm.Session{Initialized: true})
	r.Form.db.Statement.ConnPool = db.Statement.ConnPool
	return r
}

func (r response) replaceDB(db *gorm.DB) response {
	r.responseDo.ReplaceDB(db)
	r.Form.db = db.Session(&gorm.Session{})
	return r
}

type responseBelongsToForm struct {
	db *gorm.DB

	field.RelationField

	Project struct {
		field.RelationField
		Team struct {
			field.RelationField
			Plan struct {
				field.RelationField
				Coupons struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Features struct {
					field.RelationField
					Plan struct {
						field.RelationField
					}
				}
				Teams struct {
					field.RelationField
				}
			}
			TeamUsage struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
			}
			Forms struct {
				field.RelationField
			}
			Projects struct {
				field.RelationField
			}
		}
		Forms struct {
			field.RelationField
		}
	}
	Team struct {
		field.RelationField
	}
	ActivePasswords struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
	Edges struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
		SourceNode struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			Options struct {
				field.RelationField
				Question struct {
					field.RelationField
				}
			}
			OutgoingEdges struct {
				field.RelationField
			}
			IncomingEdges struct {
				field.RelationField
			}
		}
		TargetNode struct {
			field.RelationField
		}
	}
	Questions struct {
		field.RelationField
	}
	Responses struct {
		field.RelationField
		Form struct {
			field.RelationField
		}
	}
}

func (a responseBelongsToForm) Where(conds ...field.Expr) *responseBelongsToForm {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a responseBelongsToForm) WithContext(ctx context.Context) *responseBelongsToForm {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a responseBelongsToForm) Session(session *gorm.Session) *responseBelongsToForm {
	a.db = a.db.Session(session)
	return &a
}

func (a responseBelongsToForm) Model(m *models.Response) *responseBelongsToFormTx {
	return &responseBelongsToFormTx{a.db.Model(m).Association(a.Name())}
}

func (a responseBelongsToForm) Unscoped() *responseBelongsToForm {
	a.db = a.db.Unscoped()
	return &a
}

type responseBelongsToFormTx struct{ tx *gorm.Association }

func (a responseBelongsToFormTx) Find() (result *models.Form, err error) {
	return result, a.tx.Find(&result)
}

func (a responseBelongsToFormTx) Append(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a responseBelongsToFormTx) Replace(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a responseBelongsToFormTx) Delete(values ...*models.Form) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a responseBelongsToFormTx) Clear() error {
	return a.tx.Clear()
}

func (a responseBelongsToFormTx) Count() int64 {
	return a.tx.Count()
}

func (a responseBelongsToFormTx) Unscoped() *responseBelongsToFormTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type responseDo struct{ gen.DO }

type IResponseDo interface {
	gen.SubQuery
	Debug() IResponseDo
	WithContext(ctx context.Context) IResponseDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IResponseDo
	WriteDB() IResponseDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IResponseDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IResponseDo
	Not(conds ...gen.Condition) IResponseDo
	Or(conds ...gen.Condition) IResponseDo
	Select(conds ...field.Expr) IResponseDo
	Where(conds ...gen.Condition) IResponseDo
	Order(conds ...field.Expr) IResponseDo
	Distinct(cols ...field.Expr) IResponseDo
	Omit(cols ...field.Expr) IResponseDo
	Join(table schema.Tabler, on ...field.Expr) IResponseDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IResponseDo
	RightJoin(table schema.Tabler, on ...field.Expr) IResponseDo
	Group(cols ...field.Expr) IResponseDo
	Having(conds ...gen.Condition) IResponseDo
	Limit(limit int) IResponseDo
	Offset(offset int) IResponseDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IResponseDo
	Unscoped() IResponseDo
	Create(values ...*models.Response) error
	CreateInBatches(values []*models.Response, batchSize int) error
	Save(values ...*models.Response) error
	First() (*models.Response, error)
	Take() (*models.Response, error)
	Last() (*models.Response, error)
	Find() ([]*models.Response, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Response, err error)
	FindInBatches(result *[]*models.Response, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Response) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IResponseDo
	Assign(attrs ...field.AssignExpr) IResponseDo
	Joins(fields ...field.RelationField) IResponseDo
	Preload(fields ...field.RelationField) IResponseDo
	FirstOrInit() (*models.Response, error)
	FirstOrCreate() (*models.Response, error)
	FindByPage(offset int, limit int) (result []*models.Response, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IResponseDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r responseDo) Debug() IResponseDo {
	return r.withDO(r.DO.Debug())
}

func (r responseDo) WithContext(ctx context.Context) IResponseDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r responseDo) ReadDB() IResponseDo {
	return r.Clauses(dbresolver.Read)
}

func (r responseDo) WriteDB() IResponseDo {
	return r.Clauses(dbresolver.Write)
}

func (r responseDo) Session(config *gorm.Session) IResponseDo {
	return r.withDO(r.DO.Session(config))
}

func (r responseDo) Clauses(conds ...clause.Expression) IResponseDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r responseDo) Returning(value interface{}, columns ...string) IResponseDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r responseDo) Not(conds ...gen.Condition) IResponseDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r responseDo) Or(conds ...gen.Condition) IResponseDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r responseDo) Select(conds ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r responseDo) Where(conds ...gen.Condition) IResponseDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r responseDo) Order(conds ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r responseDo) Distinct(cols ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r responseDo) Omit(cols ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r responseDo) Join(table schema.Tabler, on ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r responseDo) LeftJoin(table schema.Tabler, on ...field.Expr) IResponseDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r responseDo) RightJoin(table schema.Tabler, on ...field.Expr) IResponseDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r responseDo) Group(cols ...field.Expr) IResponseDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r responseDo) Having(conds ...gen.Condition) IResponseDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r responseDo) Limit(limit int) IResponseDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r responseDo) Offset(offset int) IResponseDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r responseDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IResponseDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r responseDo) Unscoped() IResponseDo {
	return r.withDO(r.DO.Unscoped())
}

func (r responseDo) Create(values ...*models.Response) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r responseDo) CreateInBatches(values []*models.Response, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r responseDo) Save(values ...*models.Response) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r responseDo) First() (*models.Response, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Response), nil
	}
}

func (r responseDo) Take() (*models.Response, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Response), nil
	}
}

func (r responseDo) Last() (*models.Response, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Response), nil
	}
}

func (r responseDo) Find() ([]*models.Response, error) {
	result, err := r.DO.Find()
	return result.([]*models.Response), err
}

func (r responseDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Response, err error) {
	buf := make([]*models.Response, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r responseDo) FindInBatches(result *[]*models.Response, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r responseDo) Attrs(attrs ...field.AssignExpr) IResponseDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r responseDo) Assign(attrs ...field.AssignExpr) IResponseDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r responseDo) Joins(fields ...field.RelationField) IResponseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r responseDo) Preload(fields ...field.RelationField) IResponseDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r responseDo) FirstOrInit() (*models.Response, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Response), nil
	}
}

func (r responseDo) FirstOrCreate() (*models.Response, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Response), nil
	}
}

func (r responseDo) FindByPage(offset int, limit int) (result []*models.Response, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r responseDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r responseDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r responseDo) Delete(models ...*models.Response) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *responseDo) withDO(do gen.Dao) *responseDo {
	r.DO = *do.(*gen.DO)
	return r
}
