// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newTeamUsage(db *gorm.DB, opts ...gen.DOOption) teamUsage {
	_teamUsage := teamUsage{}

	_teamUsage.teamUsageDo.UseDB(db, opts...)
	_teamUsage.teamUsageDo.UseModel(&models.TeamUsage{})

	tableName := _teamUsage.teamUsageDo.TableName()
	_teamUsage.ALL = field.NewAsterisk(tableName)
	_teamUsage.ID = field.NewString(tableName, "id")
	_teamUsage.TeamID = field.NewString(tableName, "teamId")
	_teamUsage.FormsAllowed = field.NewInt(tableName, "formsAllowed")
	_teamUsage.ProjectsAllowed = field.NewInt(tableName, "projectsAllowed")
	_teamUsage.Responses = field.NewInt(tableName, "responses")
	_teamUsage.OverUsage = field.NewInt(tableName, "overUsage")
	_teamUsage.CycleStart = field.NewTime(tableName, "cycleStart")
	_teamUsage.CycleEnd = field.NewTime(tableName, "cycleEnd")
	_teamUsage.Status = field.NewString(tableName, "status")
	_teamUsage.CreatedAt = field.NewTime(tableName, "createdAt")
	_teamUsage.UpdatedAt = field.NewTime(tableName, "updatedAt")
	_teamUsage.Team = teamUsageBelongsToTeam{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Team", "models.Team"),
		Plan: struct {
			field.RelationField
			Coupons struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}
			Features struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}
			Teams struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Team.Plan", "models.Plan"),
			Coupons: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Plan.Coupons", "models.Coupon"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Plan.Coupons.Plan", "models.Plan"),
				},
			},
			Features: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Plan.Features", "models.Feature"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Plan.Features.Plan", "models.Plan"),
				},
			},
			Teams: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Plan.Teams", "models.Team"),
			},
		},
		TeamUsage: struct {
			field.RelationField
			Team struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Team.TeamUsage", "models.TeamUsage"),
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.TeamUsage.Team", "models.Team"),
			},
		},
		Forms: struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Team.Forms", "models.Form"),
			Project: struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Project", "models.Project"),
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Project.Team", "models.Team"),
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Project.Forms", "models.Form"),
				},
			},
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Forms.Team", "models.Team"),
			},
			ActivePasswords: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.ActivePasswords", "models.ActivePassword"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.ActivePasswords.Form", "models.Form"),
				},
			},
			Edges: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Edges", "models.Edge"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.Form", "models.Form"),
				},
				SourceNode: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.SourceNode", "models.Question"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Form", "models.Form"),
					},
					Options: struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Options", "models.QuestionOption"),
						Question: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Options.Question", "models.Question"),
						},
					},
					OutgoingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
					},
					IncomingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
					},
				},
				TargetNode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.TargetNode", "models.Question"),
				},
			},
			Questions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Forms.Questions", "models.Question"),
			},
			Responses: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Responses", "models.Response"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Responses.Form", "models.Form"),
				},
			},
		},
		Projects: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Team.Projects", "models.Project"),
		},
	}

	_teamUsage.fillFieldMap()

	return _teamUsage
}

type teamUsage struct {
	teamUsageDo

	ALL             field.Asterisk
	ID              field.String
	TeamID          field.String
	FormsAllowed    field.Int
	ProjectsAllowed field.Int
	Responses       field.Int
	OverUsage       field.Int
	CycleStart      field.Time
	CycleEnd        field.Time
	Status          field.String
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Team            teamUsageBelongsToTeam

	fieldMap map[string]field.Expr
}

func (t teamUsage) Table(newTableName string) *teamUsage {
	t.teamUsageDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t teamUsage) As(alias string) *teamUsage {
	t.teamUsageDo.DO = *(t.teamUsageDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *teamUsage) updateTableName(table string) *teamUsage {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.TeamID = field.NewString(table, "teamId")
	t.FormsAllowed = field.NewInt(table, "formsAllowed")
	t.ProjectsAllowed = field.NewInt(table, "projectsAllowed")
	t.Responses = field.NewInt(table, "responses")
	t.OverUsage = field.NewInt(table, "overUsage")
	t.CycleStart = field.NewTime(table, "cycleStart")
	t.CycleEnd = field.NewTime(table, "cycleEnd")
	t.Status = field.NewString(table, "status")
	t.CreatedAt = field.NewTime(table, "createdAt")
	t.UpdatedAt = field.NewTime(table, "updatedAt")

	t.fillFieldMap()

	return t
}

func (t *teamUsage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *teamUsage) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["teamId"] = t.TeamID
	t.fieldMap["formsAllowed"] = t.FormsAllowed
	t.fieldMap["projectsAllowed"] = t.ProjectsAllowed
	t.fieldMap["responses"] = t.Responses
	t.fieldMap["overUsage"] = t.OverUsage
	t.fieldMap["cycleStart"] = t.CycleStart
	t.fieldMap["cycleEnd"] = t.CycleEnd
	t.fieldMap["status"] = t.Status
	t.fieldMap["createdAt"] = t.CreatedAt
	t.fieldMap["updatedAt"] = t.UpdatedAt

}

func (t teamUsage) clone(db *gorm.DB) teamUsage {
	t.teamUsageDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Team.db = db.Session(&gorm.Session{Initialized: true})
	t.Team.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t teamUsage) replaceDB(db *gorm.DB) teamUsage {
	t.teamUsageDo.ReplaceDB(db)
	t.Team.db = db.Session(&gorm.Session{})
	return t
}

type teamUsageBelongsToTeam struct {
	db *gorm.DB

	field.RelationField

	Plan struct {
		field.RelationField
		Coupons struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}
		Features struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}
		Teams struct {
			field.RelationField
		}
	}
	TeamUsage struct {
		field.RelationField
		Team struct {
			field.RelationField
		}
	}
	Forms struct {
		field.RelationField
		Project struct {
			field.RelationField
			Team struct {
				field.RelationField
			}
			Forms struct {
				field.RelationField
			}
		}
		Team struct {
			field.RelationField
		}
		ActivePasswords struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
		Edges struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}
		Questions struct {
			field.RelationField
		}
		Responses struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
	}
	Projects struct {
		field.RelationField
	}
}

func (a teamUsageBelongsToTeam) Where(conds ...field.Expr) *teamUsageBelongsToTeam {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a teamUsageBelongsToTeam) WithContext(ctx context.Context) *teamUsageBelongsToTeam {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a teamUsageBelongsToTeam) Session(session *gorm.Session) *teamUsageBelongsToTeam {
	a.db = a.db.Session(session)
	return &a
}

func (a teamUsageBelongsToTeam) Model(m *models.TeamUsage) *teamUsageBelongsToTeamTx {
	return &teamUsageBelongsToTeamTx{a.db.Model(m).Association(a.Name())}
}

func (a teamUsageBelongsToTeam) Unscoped() *teamUsageBelongsToTeam {
	a.db = a.db.Unscoped()
	return &a
}

type teamUsageBelongsToTeamTx struct{ tx *gorm.Association }

func (a teamUsageBelongsToTeamTx) Find() (result *models.Team, err error) {
	return result, a.tx.Find(&result)
}

func (a teamUsageBelongsToTeamTx) Append(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a teamUsageBelongsToTeamTx) Replace(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a teamUsageBelongsToTeamTx) Delete(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a teamUsageBelongsToTeamTx) Clear() error {
	return a.tx.Clear()
}

func (a teamUsageBelongsToTeamTx) Count() int64 {
	return a.tx.Count()
}

func (a teamUsageBelongsToTeamTx) Unscoped() *teamUsageBelongsToTeamTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type teamUsageDo struct{ gen.DO }

type ITeamUsageDo interface {
	gen.SubQuery
	Debug() ITeamUsageDo
	WithContext(ctx context.Context) ITeamUsageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITeamUsageDo
	WriteDB() ITeamUsageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITeamUsageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITeamUsageDo
	Not(conds ...gen.Condition) ITeamUsageDo
	Or(conds ...gen.Condition) ITeamUsageDo
	Select(conds ...field.Expr) ITeamUsageDo
	Where(conds ...gen.Condition) ITeamUsageDo
	Order(conds ...field.Expr) ITeamUsageDo
	Distinct(cols ...field.Expr) ITeamUsageDo
	Omit(cols ...field.Expr) ITeamUsageDo
	Join(table schema.Tabler, on ...field.Expr) ITeamUsageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITeamUsageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITeamUsageDo
	Group(cols ...field.Expr) ITeamUsageDo
	Having(conds ...gen.Condition) ITeamUsageDo
	Limit(limit int) ITeamUsageDo
	Offset(offset int) ITeamUsageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITeamUsageDo
	Unscoped() ITeamUsageDo
	Create(values ...*models.TeamUsage) error
	CreateInBatches(values []*models.TeamUsage, batchSize int) error
	Save(values ...*models.TeamUsage) error
	First() (*models.TeamUsage, error)
	Take() (*models.TeamUsage, error)
	Last() (*models.TeamUsage, error)
	Find() ([]*models.TeamUsage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TeamUsage, err error)
	FindInBatches(result *[]*models.TeamUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.TeamUsage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITeamUsageDo
	Assign(attrs ...field.AssignExpr) ITeamUsageDo
	Joins(fields ...field.RelationField) ITeamUsageDo
	Preload(fields ...field.RelationField) ITeamUsageDo
	FirstOrInit() (*models.TeamUsage, error)
	FirstOrCreate() (*models.TeamUsage, error)
	FindByPage(offset int, limit int) (result []*models.TeamUsage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITeamUsageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t teamUsageDo) Debug() ITeamUsageDo {
	return t.withDO(t.DO.Debug())
}

func (t teamUsageDo) WithContext(ctx context.Context) ITeamUsageDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t teamUsageDo) ReadDB() ITeamUsageDo {
	return t.Clauses(dbresolver.Read)
}

func (t teamUsageDo) WriteDB() ITeamUsageDo {
	return t.Clauses(dbresolver.Write)
}

func (t teamUsageDo) Session(config *gorm.Session) ITeamUsageDo {
	return t.withDO(t.DO.Session(config))
}

func (t teamUsageDo) Clauses(conds ...clause.Expression) ITeamUsageDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t teamUsageDo) Returning(value interface{}, columns ...string) ITeamUsageDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t teamUsageDo) Not(conds ...gen.Condition) ITeamUsageDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t teamUsageDo) Or(conds ...gen.Condition) ITeamUsageDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t teamUsageDo) Select(conds ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t teamUsageDo) Where(conds ...gen.Condition) ITeamUsageDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t teamUsageDo) Order(conds ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t teamUsageDo) Distinct(cols ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t teamUsageDo) Omit(cols ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t teamUsageDo) Join(table schema.Tabler, on ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t teamUsageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t teamUsageDo) RightJoin(table schema.Tabler, on ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t teamUsageDo) Group(cols ...field.Expr) ITeamUsageDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t teamUsageDo) Having(conds ...gen.Condition) ITeamUsageDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t teamUsageDo) Limit(limit int) ITeamUsageDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t teamUsageDo) Offset(offset int) ITeamUsageDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t teamUsageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITeamUsageDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t teamUsageDo) Unscoped() ITeamUsageDo {
	return t.withDO(t.DO.Unscoped())
}

func (t teamUsageDo) Create(values ...*models.TeamUsage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t teamUsageDo) CreateInBatches(values []*models.TeamUsage, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t teamUsageDo) Save(values ...*models.TeamUsage) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t teamUsageDo) First() (*models.TeamUsage, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.TeamUsage), nil
	}
}

func (t teamUsageDo) Take() (*models.TeamUsage, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.TeamUsage), nil
	}
}

func (t teamUsageDo) Last() (*models.TeamUsage, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.TeamUsage), nil
	}
}

func (t teamUsageDo) Find() ([]*models.TeamUsage, error) {
	result, err := t.DO.Find()
	return result.([]*models.TeamUsage), err
}

func (t teamUsageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.TeamUsage, err error) {
	buf := make([]*models.TeamUsage, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t teamUsageDo) FindInBatches(result *[]*models.TeamUsage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t teamUsageDo) Attrs(attrs ...field.AssignExpr) ITeamUsageDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t teamUsageDo) Assign(attrs ...field.AssignExpr) ITeamUsageDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t teamUsageDo) Joins(fields ...field.RelationField) ITeamUsageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t teamUsageDo) Preload(fields ...field.RelationField) ITeamUsageDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t teamUsageDo) FirstOrInit() (*models.TeamUsage, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.TeamUsage), nil
	}
}

func (t teamUsageDo) FirstOrCreate() (*models.TeamUsage, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.TeamUsage), nil
	}
}

func (t teamUsageDo) FindByPage(offset int, limit int) (result []*models.TeamUsage, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t teamUsageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t teamUsageDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t teamUsageDo) Delete(models ...*models.TeamUsage) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *teamUsageDo) withDO(do gen.Dao) *teamUsageDo {
	t.DO = *do.(*gen.DO)
	return t
}
