// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/HarshKanjiya/escape-form-api/internal/models"
)

func newTransaction(db *gorm.DB, opts ...gen.DOOption) transaction {
	_transaction := transaction{}

	_transaction.transactionDo.UseDB(db, opts...)
	_transaction.transactionDo.UseModel(&models.Transaction{})

	tableName := _transaction.transactionDo.TableName()
	_transaction.ALL = field.NewAsterisk(tableName)
	_transaction.ID = field.NewString(tableName, "id")
	_transaction.Type = field.NewString(tableName, "type")
	_transaction.Amount = field.NewFloat64(tableName, "amount")
	_transaction.Description = field.NewString(tableName, "description")
	_transaction.CreatedAt = field.NewTime(tableName, "created_at")
	_transaction.CreatedBy = field.NewString(tableName, "created_by")
	_transaction.TeamID = field.NewString(tableName, "team_id")
	_transaction.Team = transactionBelongsToTeam{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Team", "models.Team"),
		Plan: struct {
			field.RelationField
			Coupons struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}
			Features struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}
			Teams struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Team.Plan", "models.Plan"),
			Coupons: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Plan.Coupons", "models.Coupon"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Plan.Coupons.Plan", "models.Plan"),
				},
			},
			Features: struct {
				field.RelationField
				Plan struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Plan.Features", "models.Feature"),
				Plan: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Plan.Features.Plan", "models.Plan"),
				},
			},
			Teams: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Plan.Teams", "models.Team"),
			},
		},
		Forms: struct {
			field.RelationField
			Project struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}
			Team struct {
				field.RelationField
			}
			ActivePasswords struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
			Edges struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}
			Questions struct {
				field.RelationField
			}
			Responses struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}
		}{
			RelationField: field.NewRelation("Team.Forms", "models.Form"),
			Project: struct {
				field.RelationField
				Team struct {
					field.RelationField
				}
				Forms struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Project", "models.Project"),
				Team: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Project.Team", "models.Team"),
				},
				Forms: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Project.Forms", "models.Form"),
				},
			},
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Forms.Team", "models.Team"),
			},
			ActivePasswords: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.ActivePasswords", "models.ActivePassword"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.ActivePasswords.Form", "models.Form"),
				},
			},
			Edges: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				SourceNode struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}
				TargetNode struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Edges", "models.Edge"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.Form", "models.Form"),
				},
				SourceNode: struct {
					field.RelationField
					Form struct {
						field.RelationField
					}
					Options struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}
					OutgoingEdges struct {
						field.RelationField
					}
					IncomingEdges struct {
						field.RelationField
					}
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.SourceNode", "models.Question"),
					Form: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Form", "models.Form"),
					},
					Options: struct {
						field.RelationField
						Question struct {
							field.RelationField
						}
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Options", "models.QuestionOption"),
						Question: struct {
							field.RelationField
						}{
							RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.Options.Question", "models.Question"),
						},
					},
					OutgoingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.OutgoingEdges", "models.Edge"),
					},
					IncomingEdges: struct {
						field.RelationField
					}{
						RelationField: field.NewRelation("Team.Forms.Edges.SourceNode.IncomingEdges", "models.Edge"),
					},
				},
				TargetNode: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Edges.TargetNode", "models.Question"),
				},
			},
			Questions: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Forms.Questions", "models.Question"),
			},
			Responses: struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
			}{
				RelationField: field.NewRelation("Team.Forms.Responses", "models.Response"),
				Form: struct {
					field.RelationField
				}{
					RelationField: field.NewRelation("Team.Forms.Responses.Form", "models.Form"),
				},
			},
		},
		Projects: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Team.Projects", "models.Project"),
		},
		Transactions: struct {
			field.RelationField
			Team struct {
				field.RelationField
			}
		}{
			RelationField: field.NewRelation("Team.Transactions", "models.Transaction"),
			Team: struct {
				field.RelationField
			}{
				RelationField: field.NewRelation("Team.Transactions.Team", "models.Team"),
			},
		},
	}

	_transaction.fillFieldMap()

	return _transaction
}

type transaction struct {
	transactionDo

	ALL         field.Asterisk
	ID          field.String
	Type        field.String
	Amount      field.Float64
	Description field.String
	CreatedAt   field.Time
	CreatedBy   field.String
	TeamID      field.String
	Team        transactionBelongsToTeam

	fieldMap map[string]field.Expr
}

func (t transaction) Table(newTableName string) *transaction {
	t.transactionDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t transaction) As(alias string) *transaction {
	t.transactionDo.DO = *(t.transactionDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *transaction) updateTableName(table string) *transaction {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewString(table, "id")
	t.Type = field.NewString(table, "type")
	t.Amount = field.NewFloat64(table, "amount")
	t.Description = field.NewString(table, "description")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.CreatedBy = field.NewString(table, "created_by")
	t.TeamID = field.NewString(table, "team_id")

	t.fillFieldMap()

	return t
}

func (t *transaction) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *transaction) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["id"] = t.ID
	t.fieldMap["type"] = t.Type
	t.fieldMap["amount"] = t.Amount
	t.fieldMap["description"] = t.Description
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["created_by"] = t.CreatedBy
	t.fieldMap["team_id"] = t.TeamID

}

func (t transaction) clone(db *gorm.DB) transaction {
	t.transactionDo.ReplaceConnPool(db.Statement.ConnPool)
	t.Team.db = db.Session(&gorm.Session{Initialized: true})
	t.Team.db.Statement.ConnPool = db.Statement.ConnPool
	return t
}

func (t transaction) replaceDB(db *gorm.DB) transaction {
	t.transactionDo.ReplaceDB(db)
	t.Team.db = db.Session(&gorm.Session{})
	return t
}

type transactionBelongsToTeam struct {
	db *gorm.DB

	field.RelationField

	Plan struct {
		field.RelationField
		Coupons struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}
		Features struct {
			field.RelationField
			Plan struct {
				field.RelationField
			}
		}
		Teams struct {
			field.RelationField
		}
	}
	Forms struct {
		field.RelationField
		Project struct {
			field.RelationField
			Team struct {
				field.RelationField
			}
			Forms struct {
				field.RelationField
			}
		}
		Team struct {
			field.RelationField
		}
		ActivePasswords struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
		Edges struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
			SourceNode struct {
				field.RelationField
				Form struct {
					field.RelationField
				}
				Options struct {
					field.RelationField
					Question struct {
						field.RelationField
					}
				}
				OutgoingEdges struct {
					field.RelationField
				}
				IncomingEdges struct {
					field.RelationField
				}
			}
			TargetNode struct {
				field.RelationField
			}
		}
		Questions struct {
			field.RelationField
		}
		Responses struct {
			field.RelationField
			Form struct {
				field.RelationField
			}
		}
	}
	Projects struct {
		field.RelationField
	}
	Transactions struct {
		field.RelationField
		Team struct {
			field.RelationField
		}
	}
}

func (a transactionBelongsToTeam) Where(conds ...field.Expr) *transactionBelongsToTeam {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a transactionBelongsToTeam) WithContext(ctx context.Context) *transactionBelongsToTeam {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a transactionBelongsToTeam) Session(session *gorm.Session) *transactionBelongsToTeam {
	a.db = a.db.Session(session)
	return &a
}

func (a transactionBelongsToTeam) Model(m *models.Transaction) *transactionBelongsToTeamTx {
	return &transactionBelongsToTeamTx{a.db.Model(m).Association(a.Name())}
}

func (a transactionBelongsToTeam) Unscoped() *transactionBelongsToTeam {
	a.db = a.db.Unscoped()
	return &a
}

type transactionBelongsToTeamTx struct{ tx *gorm.Association }

func (a transactionBelongsToTeamTx) Find() (result *models.Team, err error) {
	return result, a.tx.Find(&result)
}

func (a transactionBelongsToTeamTx) Append(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a transactionBelongsToTeamTx) Replace(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a transactionBelongsToTeamTx) Delete(values ...*models.Team) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a transactionBelongsToTeamTx) Clear() error {
	return a.tx.Clear()
}

func (a transactionBelongsToTeamTx) Count() int64 {
	return a.tx.Count()
}

func (a transactionBelongsToTeamTx) Unscoped() *transactionBelongsToTeamTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type transactionDo struct{ gen.DO }

type ITransactionDo interface {
	gen.SubQuery
	Debug() ITransactionDo
	WithContext(ctx context.Context) ITransactionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITransactionDo
	WriteDB() ITransactionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITransactionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITransactionDo
	Not(conds ...gen.Condition) ITransactionDo
	Or(conds ...gen.Condition) ITransactionDo
	Select(conds ...field.Expr) ITransactionDo
	Where(conds ...gen.Condition) ITransactionDo
	Order(conds ...field.Expr) ITransactionDo
	Distinct(cols ...field.Expr) ITransactionDo
	Omit(cols ...field.Expr) ITransactionDo
	Join(table schema.Tabler, on ...field.Expr) ITransactionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITransactionDo
	Group(cols ...field.Expr) ITransactionDo
	Having(conds ...gen.Condition) ITransactionDo
	Limit(limit int) ITransactionDo
	Offset(offset int) ITransactionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionDo
	Unscoped() ITransactionDo
	Create(values ...*models.Transaction) error
	CreateInBatches(values []*models.Transaction, batchSize int) error
	Save(values ...*models.Transaction) error
	First() (*models.Transaction, error)
	Take() (*models.Transaction, error)
	Last() (*models.Transaction, error)
	Find() ([]*models.Transaction, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Transaction, err error)
	FindInBatches(result *[]*models.Transaction, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.Transaction) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITransactionDo
	Assign(attrs ...field.AssignExpr) ITransactionDo
	Joins(fields ...field.RelationField) ITransactionDo
	Preload(fields ...field.RelationField) ITransactionDo
	FirstOrInit() (*models.Transaction, error)
	FirstOrCreate() (*models.Transaction, error)
	FindByPage(offset int, limit int) (result []*models.Transaction, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITransactionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t transactionDo) Debug() ITransactionDo {
	return t.withDO(t.DO.Debug())
}

func (t transactionDo) WithContext(ctx context.Context) ITransactionDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t transactionDo) ReadDB() ITransactionDo {
	return t.Clauses(dbresolver.Read)
}

func (t transactionDo) WriteDB() ITransactionDo {
	return t.Clauses(dbresolver.Write)
}

func (t transactionDo) Session(config *gorm.Session) ITransactionDo {
	return t.withDO(t.DO.Session(config))
}

func (t transactionDo) Clauses(conds ...clause.Expression) ITransactionDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t transactionDo) Returning(value interface{}, columns ...string) ITransactionDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t transactionDo) Not(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t transactionDo) Or(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t transactionDo) Select(conds ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t transactionDo) Where(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t transactionDo) Order(conds ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t transactionDo) Distinct(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t transactionDo) Omit(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t transactionDo) Join(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t transactionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t transactionDo) RightJoin(table schema.Tabler, on ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t transactionDo) Group(cols ...field.Expr) ITransactionDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t transactionDo) Having(conds ...gen.Condition) ITransactionDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t transactionDo) Limit(limit int) ITransactionDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t transactionDo) Offset(offset int) ITransactionDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t transactionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITransactionDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t transactionDo) Unscoped() ITransactionDo {
	return t.withDO(t.DO.Unscoped())
}

func (t transactionDo) Create(values ...*models.Transaction) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t transactionDo) CreateInBatches(values []*models.Transaction, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t transactionDo) Save(values ...*models.Transaction) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t transactionDo) First() (*models.Transaction, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Take() (*models.Transaction, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Last() (*models.Transaction, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) Find() ([]*models.Transaction, error) {
	result, err := t.DO.Find()
	return result.([]*models.Transaction), err
}

func (t transactionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Transaction, err error) {
	buf := make([]*models.Transaction, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t transactionDo) FindInBatches(result *[]*models.Transaction, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t transactionDo) Attrs(attrs ...field.AssignExpr) ITransactionDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t transactionDo) Assign(attrs ...field.AssignExpr) ITransactionDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t transactionDo) Joins(fields ...field.RelationField) ITransactionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t transactionDo) Preload(fields ...field.RelationField) ITransactionDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t transactionDo) FirstOrInit() (*models.Transaction, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) FirstOrCreate() (*models.Transaction, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Transaction), nil
	}
}

func (t transactionDo) FindByPage(offset int, limit int) (result []*models.Transaction, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t transactionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t transactionDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t transactionDo) Delete(models ...*models.Transaction) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *transactionDo) withDO(do gen.Dao) *transactionDo {
	t.DO = *do.(*gen.DO)
	return t
}
